from __future__ import annotations


def file_preamble() -> str:
    return (
        "// Generated by LuauAPI codegen\n\n"
        '#include "framework/BindingHost.hpp"\n'
        '#include "framework/Binding.hpp"\n'
        '#include "framework/usertype/LuaRef.hpp"\n'
        '#include "framework/callback/LuaCallback.hpp"\n'
        '#include "framework/callback/LuaMenuHandler.hpp"\n'
        '#include "framework/callback/LuaDelegate.hpp"\n'
        '#include "framework/callback/LuaDelegates.gen.hpp"\n'
        '#include "framework/callback/LuaSelectorHandler.hpp"\n'
        '#include "framework/callback/LuaTrampolineRegistry.hpp"\n'
        '#include "framework/view/ReadOnlyVectorView.hpp"\n'
        '#include "framework/view/ReadOnlyCCArrayView.hpp"\n'
        '#include "framework/stack/ContainerTables.hpp"\n'
        '#include "framework/stack/Stack.hpp"\n'
        '#include "framework/stack/TableUtil.hpp"\n'
        '#include "framework/stack/Types.hpp"\n'
        '#include "framework/usertype/OpaqueHandle.hpp"\n'
        '#include "framework/usertype/Usertype.hpp"\n\n'
        "#include <Geode/Geode.hpp>\n"
        "#include <Geode/loader/Hook.hpp>\n"
        "#include <Geode/loader/Mod.hpp>\n"
        "#include <Geode/loader/Tulip.hpp>\n"
        "#include <cocos2d.h>\n"
        "#include <fmod_common.h>\n"
        "#include <lua.h>\n\n"
        "namespace FMOD {\n"
        "    class Channel;\n"
        "    class Sound;\n"
        "    class ChannelGroup;\n"
        "}\n\n"
        "#if defined(GEODE_IS_ANDROID) || defined(GEODE_IS_MACOS) || defined(GEODE_IS_IOS)\n"
        "#include <dlfcn.h>\n"
        "#endif\n\n"
        "#include <cstddef>\n"
        "#include <algorithm>\n"
        "#include <memory>\n"
        "#include <optional>\n"
        "#include <string>\n"
        "#include <string_view>\n"
        "#include <unordered_map>\n"
        "#include <vector>\n\n"
    )


def emit_internal_hpp() -> str:
    return (
        "// Generated by LuauAPI codegen\n\n"
        "#pragma once\n\n"
        '#include "framework/BindingHost.hpp"\n'
        '#include "core/Runtime.hpp"\n'
        '#include "framework/usertype/Fields.hpp"\n'
        '#include "framework/usertype/LuaRef.hpp"\n\n'
        "#include <Geode/Geode.hpp>\n"
        "#include <Geode/loader/Hook.hpp>\n\n"
        "#include <cstddef>\n"
        "#include <algorithm>\n"
        "#include <memory>\n"
        "#include <string>\n"
        "#include <thread>\n"
        "#include <unordered_map>\n"
        "#include <vector>\n\n"
        "namespace luauapi_gen {\n"
        "using CreateHookFn = geode::Result<geode::Hook*>(*)(std::string const&);\n\n"
        "struct LuaHookTarget {\n"
        "    char const* id;\n"
        "    char const* displayName;\n"
        "    CreateHookFn createHook;\n"
        "};\n\n"
        "struct LuaHookCallback {\n"
        "    std::size_t id = 0;\n"
        "    int kind = 0;\n"
        "    int priority = 0;\n"
        "    std::size_t installOrder = 0;\n"
        "    luax::LuaRef ref;\n"
        "    bool removed = false;\n"
        "};\n\n"
        "struct LuaHookState {\n"
        "    LuaHookTarget const* target = nullptr;\n"
        "    geode::Hook* hook = nullptr;\n"
        "    std::vector<std::shared_ptr<LuaHookCallback>> callbacks;\n"
        "    std::vector<std::shared_ptr<LuaHookCallback>> preSorted;\n"
        "    std::vector<std::shared_ptr<LuaHookCallback>> postSorted;\n"
        "};\n\n"
        "std::unordered_map<std::string, LuaHookState>& hookStates();\n\n"
        "#if defined(GEODE_IS_ANDROID)\n"
        "void* luaapi_android_libcocos();\n"
        "#endif\n\n"
        "inline int normalizeLuaIndex(lua_State* L, int idx) {\n"
        "    return idx < 0 ? lua_gettop(L) + idx + 1 : idx;\n"
        "}\n\n"
        "inline bool applyHookOverride(lua_State* L, int valueIdx, lua_CFunction fn, void* ctx, char const* targetId) {\n"
        "    auto* host = luax::BindingHost::fromState(L);\n"
        "    if (!host) {\n"
        '        geode::log::error("luau hook [{}] override rejected: binding host unavailable", targetId);\n'
        "        return false;\n"
        "    }\n"
        "    int top = lua_gettop(L);\n"
        "    int absValue = normalizeLuaIndex(L, valueIdx);\n"
        "    lua_pushlightuserdata(L, ctx);\n"
        "    lua_pushcclosure(L, fn, nullptr, 1);\n"
        "    lua_pushvalue(L, absValue);\n"
        "    if (host->protectedCallWithTraceback(L, 1, 0, targetId).isErr()) {\n"
        "        lua_settop(L, top);\n"
        "        return false;\n"
        "    }\n"
        "    lua_settop(L, top);\n"
        "    return true;\n"
        "}\n\n"
        "inline void adoptMacHookThread() {\n"
        "#if defined(GEODE_IS_MACOS)\n"
        "    if (!luax::Runtime::isMainThread()) {\n"
        "        luax::Runtime::setMainThreadId(std::this_thread::get_id());\n"
        "    }\n"
        "#endif\n"
        "}\n\n"
        "template <class PushContext, class ApplyArgs, class ApplySkip>\n"
        "bool runLuaPreHooks(char const* targetId, int nargs, PushContext pushContext, ApplyArgs applyArgs, ApplySkip applySkip) {\n"
        "    adoptMacHookThread();\n"
        "    auto it = hookStates().find(targetId);\n"
        "    if (it == hookStates().end()) return false;\n"
        "    auto const& callbacks = it->second.preSorted;\n"
        "    auto* host = luax::BindingHost::getIfInitialized();\n"
        "    if (!host || !host->ready()) return false;\n"
        "    auto* L = host->state();\n"
        "    if (!L) return false;\n"
        "    for (auto const& callback : callbacks) {\n"
        "        if (!callback || callback->kind != 0 || callback->removed || !callback->ref.valid()) continue;\n"
        "        int top = lua_gettop(L);\n"
        "        if (!callback->ref.push()) {\n"
        "            lua_settop(L, top);\n"
        "            continue;\n"
        "        }\n"
        "        pushContext(L);\n"
        "        luax::BindingHost::ResourcesRootScope rootScope(*host, callback->ref.resourcesRoot());\n"
        "        if (host->protectedCall(L, nargs, 1, targetId, luax::kHookScriptDeadlineMs).isOk()) {\n"
        "            if (lua_istable(L, -1)) {\n"
        "                int resultIdx = normalizeLuaIndex(L, -1);\n"
        '                lua_getfield(L, resultIdx, "__luauapi_skip");\n'
        "                bool skip = lua_toboolean(L, -1) != 0;\n"
        "                lua_pop(L, 1);\n"
        "                if (skip) {\n"
        '                    lua_getfield(L, resultIdx, "value");\n'
        "                    if (!applySkip(L, -1)) {\n"
        "                        lua_pop(L, 1);\n"
        "                        lua_settop(L, top);\n"
        "                        continue;\n"
        "                    }\n"
        "                    lua_pop(L, 1);\n"
        "                    lua_settop(L, top);\n"
        "                    return true;\n"
        "                }\n"
        '                lua_getfield(L, resultIdx, "args");\n'
        "                if (!lua_isnil(L, -1)) applyArgs(L, -1);\n"
        "                lua_pop(L, 1);\n"
        "            } else if (!lua_isnil(L, -1)) {\n"
        '                geode::log::error("luau hook [{}] returned invalid before result", targetId);\n'
        "            }\n"
        "        }\n"
        "        lua_settop(L, top);\n"
        "    }\n"
        "    return false;\n"
        "}\n\n"
        "template <class PushContext, class ApplyReturn>\n"
        "void runLuaPostHooks(char const* targetId, int nargs, PushContext pushContext, ApplyReturn applyReturn) {\n"
        "    adoptMacHookThread();\n"
        "    auto it = hookStates().find(targetId);\n"
        "    if (it == hookStates().end()) return;\n"
        "    auto const& callbacks = it->second.postSorted;\n"
        "    auto* host = luax::BindingHost::getIfInitialized();\n"
        "    if (!host || !host->ready()) return;\n"
        "    auto* L = host->state();\n"
        "    if (!L) return;\n"
        "    for (auto const& callback : callbacks) {\n"
        "        if (!callback || callback->kind != 1 || callback->removed || !callback->ref.valid()) continue;\n"
        "        int top = lua_gettop(L);\n"
        "        if (!callback->ref.push()) {\n"
        "            lua_settop(L, top);\n"
        "            continue;\n"
        "        }\n"
        "        pushContext(L);\n"
        "        luax::BindingHost::ResourcesRootScope rootScope(*host, callback->ref.resourcesRoot());\n"
        "        if (host->protectedCall(L, nargs, 1, targetId, luax::kHookScriptDeadlineMs).isOk()) {\n"
        "            if (!lua_isnil(L, -1)) {\n"
        "                if (!applyReturn(L, -1)) {\n"
        "                    lua_settop(L, top);\n"
        "                    continue;\n"
        "                }\n"
        "            }\n"
        "        }\n"
        "        lua_settop(L, top);\n"
        "    }\n"
        "}\n"
        "} // namespace luauapi_gen\n"
    )


def emit_hook_support() -> str:
    return """#if defined(GEODE_IS_ANDROID)
    void* luaapi_android_libcocos() {
        static void* handle = dlopen("libcocos2dcpp.so", RTLD_NOW);
        return handle;
    }
#endif

    std::unordered_map<std::string, LuaHookState>& hookStates() {
        static auto* value = new std::unordered_map<std::string, LuaHookState>();
        return *value;
    }

    std::size_t& nextHookCallbackId() {
        static auto value = std::size_t(1);
        return value;
    }

    std::size_t& nextHookInstallOrder() {
        static auto value = std::size_t(1);
        return value;
    }

    void clearHookRegistry() {
        for (auto& [_, state] : hookStates()) {
            for (auto const& callback : state.callbacks) {
                if (callback) {
                    callback->removed = true;
                    callback->ref.reset();
                }
            }
            if (state.hook && state.hook->isEnabled()) {
                auto result = state.hook->disable();
                if (result.isErr()) {
                    geode::log::warn("luau hook disable failed during shutdown: {}", result.unwrapErr());
                }
            }
        }
        hookStates().clear();
    }

    LuaHookState* findHookState(std::size_t callbackId) {
        for (auto& [_, state] : hookStates()) {
            for (auto const& callback : state.callbacks) {
                if (callback && callback->id == callbackId) {
                    return &state;
                }
            }
        }
        return nullptr;
    }

    std::shared_ptr<LuaHookCallback> findHookCallback(std::size_t callbackId) {
        for (auto& [_, state] : hookStates()) {
            for (auto const& callback : state.callbacks) {
                if (callback && callback->id == callbackId) {
                    return callback;
                }
            }
        }
        return nullptr;
    }

    bool stateHasLiveCallbacks(LuaHookState const& state);

    bool preHookCallbackLess(std::shared_ptr<LuaHookCallback> const& a, std::shared_ptr<LuaHookCallback> const& b) {
        if (!a || !b) return static_cast<bool>(b);
        if (a->priority != b->priority) return a->priority < b->priority;
        return a->installOrder < b->installOrder;
    }

    bool postHookCallbackLess(std::shared_ptr<LuaHookCallback> const& a, std::shared_ptr<LuaHookCallback> const& b) {
        if (!a || !b) return static_cast<bool>(b);
        if (a->priority != b->priority) return a->priority > b->priority;
        return a->installOrder > b->installOrder;
    }

    void insertPreSorted(LuaHookState& state, std::shared_ptr<LuaHookCallback> const& callback) {
        auto& list = state.preSorted;
        auto it = std::lower_bound(
            list.begin(),
            list.end(),
            callback,
            [](auto const& left, auto const& right) { return preHookCallbackLess(left, right); }
        );
        list.insert(it, callback);
    }

    void insertPostSorted(LuaHookState& state, std::shared_ptr<LuaHookCallback> const& callback) {
        auto& list = state.postSorted;
        auto it = std::lower_bound(
            list.begin(),
            list.end(),
            callback,
            [](auto const& left, auto const& right) { return postHookCallbackLess(left, right); }
        );
        list.insert(it, callback);
    }

    void rebuildSortedHookLists(LuaHookState& state) {
        state.preSorted.clear();
        state.postSorted.clear();
        for (auto const& callback : state.callbacks) {
            if (!callback || callback->removed) continue;
            if (callback->kind == 0) {
                insertPreSorted(state, callback);
            } else {
                insertPostSorted(state, callback);
            }
        }
    }

    bool removeHookCallbacks(std::size_t callbackId) {
        bool removed = false;
        for (auto& [_, state] : hookStates()) {
            for (auto const& callback : state.callbacks) {
                if (callback && callback->id == callbackId && !callback->removed) {
                    callback->removed = true;
                    callback->ref.reset();
                    removed = true;
                }
            }
            if (state.hook && !stateHasLiveCallbacks(state)) {
                auto result = state.hook->disable();
                if (result.isErr()) {
                    geode::log::warn("luau hook disable failed after remove: {}", result.unwrapErr());
                }
            }
        }
        return removed;
    }

    bool stateHasLiveCallbacks(LuaHookState const& state) {
        for (auto const& callback : state.callbacks) {
            if (callback && !callback->removed) return true;
        }
        return false;
    }

    void compactRemovedCallbacks(LuaHookState& state) {
        std::size_t out = 0;
        for (auto const& callback : state.callbacks) {
            if (callback && !callback->removed) {
                state.callbacks[out++] = callback;
            }
        }
        state.callbacks.resize(out);
        rebuildSortedHookLists(state);
    }

    std::size_t compactAndCountLiveCallbacks() {
        std::size_t total = 0;
        for (auto& [_, state] : hookStates()) {
            compactRemovedCallbacks(state);
            total += state.callbacks.size();
        }
        return total;
    }

    std::size_t hookHandleId(lua_State* L) {
        return static_cast<std::size_t>(lua_tointeger(L, lua_upvalueindex(1)));
    }

    int luaapi_hook_handle_enable(lua_State* L) {
        auto id = hookHandleId(L);
        auto callback = findHookCallback(id);
        auto* state = findHookState(id);
        if (!callback || callback->removed) {
            lua_pushboolean(L, false);
            return 1;
        }
        if (!state || !state->hook) {
            lua_pushboolean(L, false);
            return 1;
        }
        auto result = state->hook->enable();
        lua_pushboolean(L, result.isOk());
        if (result.isErr()) {
            luax::push(L, result.unwrapErr());
            return 2;
        }
        return 1;
    }

    int luaapi_hook_handle_disable(lua_State* L) {
        auto id = hookHandleId(L);
        auto callback = findHookCallback(id);
        auto* state = findHookState(id);
        if (!callback || callback->removed) {
            lua_pushboolean(L, false);
            return 1;
        }
        if (!state || !state->hook) {
            lua_pushboolean(L, false);
            return 1;
        }
        auto result = state->hook->disable();
        lua_pushboolean(L, result.isOk());
        if (result.isErr()) {
            luax::push(L, result.unwrapErr());
            return 2;
        }
        return 1;
    }

    int luaapi_hook_handle_remove(lua_State* L) {
        auto id = hookHandleId(L);
        if (!removeHookCallbacks(id)) {
            lua_pushboolean(L, false);
            return 1;
        }
        lua_pushboolean(L, true);
        return 1;
    }

    int luaapi_hook_handle_is_enabled(lua_State* L) {
        auto id = hookHandleId(L);
        auto callback = findHookCallback(id);
        auto* state = findHookState(id);
        lua_pushboolean(L, callback && !callback->removed && state && state->hook && state->hook->isEnabled());
        return 1;
    }

    void pushHookHandle(lua_State* L, std::size_t callbackId) {
        lua_createtable(L, 0, 4);
        lua_pushinteger(L, static_cast<lua_Integer>(callbackId));
        lua_pushcclosure(L, &luaapi_hook_handle_enable, nullptr, 1);
        lua_setfield(L, -2, "enable");
        lua_pushinteger(L, static_cast<lua_Integer>(callbackId));
        lua_pushcclosure(L, &luaapi_hook_handle_disable, nullptr, 1);
        lua_setfield(L, -2, "disable");
        lua_pushinteger(L, static_cast<lua_Integer>(callbackId));
        lua_pushcclosure(L, &luaapi_hook_handle_remove, nullptr, 1);
        lua_setfield(L, -2, "remove");
        lua_pushinteger(L, static_cast<lua_Integer>(callbackId));
        lua_pushcclosure(L, &luaapi_hook_handle_is_enabled, nullptr, 1);
        lua_setfield(L, -2, "isEnabled");
    }

    void ensureHookInstalled(lua_State* L, LuaHookState& state, LuaHookTarget const* target, char const* id) {
        if (!state.hook) {
            auto result = target->createHook(target->displayName);
            if (result.isErr()) {
                luaL_error(L, "geode.hook failed for %s: %s", id, result.unwrapErr().c_str());
            }
            state.hook = result.unwrap();
            if (!state.hook->isEnabled()) {
                auto enableResult = state.hook->enable();
                if (enableResult.isErr()) {
                    luaL_error(L, "geode.hook enable failed for %s: %s", id, enableResult.unwrapErr().c_str());
                }
            }
        } else if (!state.hook->isEnabled()) {
            auto result = state.hook->enable();
            if (result.isErr()) {
                luaL_error(L, "geode.hook enable failed for %s: %s", id, result.unwrapErr().c_str());
            }
        }
    }

    void appendLuaHookCallback(lua_State* L, LuaHookState& state, std::size_t handleId, int kind, int priority, int fnIndex) {
        auto callback = std::make_shared<LuaHookCallback>();
        callback->id = handleId;
        callback->kind = kind;
        callback->priority = priority;
        callback->installOrder = nextHookInstallOrder()++;
        callback->ref.reset(L, fnIndex);
        state.callbacks.push_back(callback);
        if (kind == 0) {
            insertPreSorted(state, callback);
        } else {
            insertPostSorted(state, callback);
        }
    }

    int luaapi_geode_hook(lua_State* L) {
        if (lua_gettop(L) != 2) luaL_error(L, "geode.hook expected 2 args");
        char const* id = lua_tostring(L, 1);
        if (!id || !*id) luaL_error(L, "geode.hook expected target id at arg 1");
        if (!lua_istable(L, 2)) luaL_error(L, "geode.hook expected callback table at arg 2");

        auto* target = findHookTarget(id);
        if (!target) luaL_error(L, "geode.hook target not found: %s", id);

        int priority = 0;
        lua_getfield(L, 2, "priority");
        if (!lua_isnil(L, -1)) {
            if (!lua_isnumber(L, -1)) luaL_error(L, "geode.hook priority must be a number");
            priority = static_cast<int>(lua_tointeger(L, -1));
        }
        lua_pop(L, 1);

        lua_getfield(L, 2, "before");
        bool hasBefore = lua_isfunction(L, -1);
        if (!hasBefore && !lua_isnil(L, -1)) luaL_error(L, "geode.hook before must be a function");
        int beforeIndex = lua_gettop(L);
        lua_getfield(L, 2, "after");
        bool hasAfter = lua_isfunction(L, -1);
        if (!hasAfter && !lua_isnil(L, -1)) luaL_error(L, "geode.hook after must be a function");
        int afterIndex = lua_gettop(L);
        if (!hasBefore && !hasAfter) luaL_error(L, "geode.hook expected before or after function");

        auto& state = hookStates()[id];
        state.target = target;
        auto liveTotal = compactAndCountLiveCallbacks();
        auto adding = static_cast<std::size_t>((hasBefore ? 1 : 0) + (hasAfter ? 1 : 0));
        if (liveTotal + adding > luax::kMaxHookCallbacksGlobal) {
            luaL_error(L, "geode.hook global callback limit exceeded");
        }
        if (state.callbacks.size() + adding > luax::kMaxHookCallbacksPerTarget) {
            luaL_error(L, "geode.hook target callback limit exceeded for %s", id);
        }

        ensureHookInstalled(L, state, target, id);

        auto handleId = nextHookCallbackId()++;
        if (hasBefore) appendLuaHookCallback(L, state, handleId, 0, priority, beforeIndex);
        if (hasAfter) appendLuaHookCallback(L, state, handleId, 1, priority, afterIndex);
        lua_pop(L, 2);
        pushHookHandle(L, handleId);
        return 1;
    }

    int luaapi_geode_skip(lua_State* L) {
        int argc = lua_gettop(L);
        if (argc > 1) luaL_error(L, "geode.skip expected 0 or 1 args");
        lua_createtable(L, 0, 2);
        lua_pushboolean(L, true);
        lua_setfield(L, -2, "__luauapi_skip");
        if (argc >= 1) {
            lua_pushvalue(L, 1);
        } else {
            lua_pushnil(L);
        }
        lua_setfield(L, -2, "value");
        return 1;
    }

    int luaapi_geode_fields(lua_State* L) {
        if (lua_gettop(L) != 1) luaL_error(L, "geode.fields expected 1 arg");
        auto* node = luax::detail::tryNodeCandidate(L, 1);
        if (!node) luaL_error(L, "geode.fields expected CCNode at arg 1");
        luax::Fields::push(L, node);
        return 1;
    }

"""
