from __future__ import annotations

import os
from typing import Dict, List, Tuple

from luau_codegen.parse.broma import Root
from luau_codegen.model.domain import lua_namespace
from luau_codegen.emit.plan import EmitPlan, collect_plan
from luau_codegen.emit.luau_types.classes import (
    _emit_class,
    _emitted_base_name,
    _should_emit_type_class,
    _topo_sort_chunks,
)
from luau_codegen.emit.luau_types.enums import (
    _enum_block,
    _enum_tables_block,
    enum_namespace_field_lines,
)
from luau_codegen.emit.luau_types.factories import (
    _collect_factories,
    _emit_factories,
    _emit_factory_records,
    _factory_field_lines,
)
from luau_codegen.emit.luau_types.free_fn_tree import (
    _build_function_tree,
    _emit_function_tree,
)
from luau_codegen.emit.luau_types.references import (
    _VALUE_STUB_BODY,
    _emit_delegate_stub_block,
    _emit_orphan_stubs,
    _emit_value_stub_block,
    _factory_object_refs,
    _refs_from_classes,
    _refs_from_text,
    _value_refs_in_text,
)

TYPES_FILE = "geode.d.luau"
cocos_namespace = "geode.cocos2d"
gd_namespace = "geode.gd"
geode_namespace = "geode"

__all__ = ["emit", "TYPES_FILE"]

_PACKAGE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


def _collect_extra_dluau() -> str:
    extra_dir = os.path.join(_PACKAGE_DIR, "extra_bindings")
    if not os.path.isdir(extra_dir):
        return ""
    parts: list[str] = []
    for name in sorted(os.listdir(extra_dir)):
        if name.endswith(".dluau"):
            with open(os.path.join(extra_dir, name), "r", encoding="utf-8") as f:
                parts.append(f.read().strip())
    if not parts:
        return ""
    body = "\n\n".join(parts)
    return "\n\n-- Custom definitions from tools/luau_codegen/extra_bindings/\n\n" + body + "\n"


def _header(label: str) -> List[str]:
    return [
        "-- Generated by LuauAPI codegen\n",
        f"-- {label}\n",
        "\n",
    ]


def emit(
    root: Root,
    target_platform: str = "win",
    plan: EmitPlan | None = None,
    manual_fields: Dict[str, list] | None = None,
) -> Dict[str, str]:
    if plan is None:
        plan = collect_plan(root, target_platform)
    classes = plan.classes
    objects = plan.objects
    grouped_by_class = plan.supported_by_class
    skipped_classes = plan.skipped_classes

    cocos_chunks: List[Tuple[str, str]] = []
    gd_chunks: List[Tuple[str, str]] = []
    for cls in classes:
        field_targets = plan.field_targets_by_class.get(cls.name, [])
        if not _should_emit_type_class(
            cls,
            objects,
            field_targets,
            skipped_classes,
            target_platform=target_platform,
            ctx=plan.ctx,
        ):
            continue
        grouped = grouped_by_class[cls.name]
        chunk = "".join(
            _emit_class(
                cls,
                grouped,
                field_targets,
                objects,
                skipped_classes,
                target_platform=target_platform,
                ctx=plan.ctx,
            )
        )
        if lua_namespace(cls) == cocos_namespace:
            cocos_chunks.append((cls.name, chunk))
        else:
            gd_chunks.append((cls.name, chunk))

    base_of = {
        name: _emitted_base_name(objects[name], objects, skipped_classes)
        for name in {n for n, _ in cocos_chunks} | {n for n, _ in gd_chunks}
        if name in objects
    }
    cocos_chunks = _topo_sort_chunks(cocos_chunks, base_of)
    gd_chunks = _topo_sort_chunks(gd_chunks, base_of)

    cocos_body = "".join(chunk for _, chunk in cocos_chunks)
    gd_body = "".join(chunk for _, chunk in gd_chunks)

    cocos_factories = _collect_factories(
        classes, grouped_by_class, skipped_classes, cocos_namespace
    )
    gd_factories = _collect_factories(classes, grouped_by_class, skipped_classes, gd_namespace)
    geode_factories = _collect_factories(
        classes, grouped_by_class, skipped_classes, geode_namespace
    )
    cocos_factory_text = "".join(
        _emit_factories(cocos_factories, objects, cocos_namespace, ctx=plan.ctx)
    )
    gd_factory_text = "".join(
        _emit_factories(
            gd_factories,
            objects,
            gd_namespace,
            ctx=plan.ctx,
            extra_field_lines=enum_namespace_field_lines(plan.ctx.gd_enum_members),
        )
    )

    geode_factory_text = "".join(_emit_factory_records(geode_factories, objects, ctx=plan.ctx))

    function_tree = _build_function_tree(plan.supported_free_functions, objects, manual_fields)
    function_field_lines = _emit_function_tree(function_tree, objects, 1, ctx=plan.ctx)

    defined = {name for name, _ in cocos_chunks} | {name for name, _ in gd_chunks}
    refs = _refs_from_classes(defined, grouped_by_class, objects, skipped_classes, ctx=plan.ctx)
    refs |= _factory_object_refs(cocos_factories, objects, ctx=plan.ctx)
    refs |= _factory_object_refs(gd_factories, objects, ctx=plan.ctx)
    refs |= _factory_object_refs(geode_factories, objects, ctx=plan.ctx)
    refs |= _refs_from_text(
        cocos_body + gd_body + cocos_factory_text + gd_factory_text + geode_factory_text
    )
    refs |= _refs_from_text("".join(function_field_lines))
    orphan_names = {
        name
        for name in refs
        if name not in defined and name in objects and name not in _VALUE_STUB_BODY
    }

    lines = _header("Geode type stubs")

    delegate_block = _emit_delegate_stub_block()
    value_block = _emit_value_stub_block(
        _value_refs_in_text(
            cocos_body + gd_body + cocos_factory_text + gd_factory_text + delegate_block
        )
    )
    if value_block:
        lines.append(value_block)
        lines.append("\n")

    if delegate_block:
        lines.append(delegate_block)
        lines.append("\n")

    for namespace in (cocos_namespace, gd_namespace, geode_namespace):
        enum_block = _enum_block(namespace, plan.ctx)
        if enum_block:
            lines.append(enum_block)
            lines.append("\n")

    enum_tables_block = _enum_tables_block(plan.ctx)
    if enum_tables_block:
        lines.append(enum_tables_block)
        lines.append("\n")

    orphan_block = _emit_orphan_stubs(orphan_names)
    if orphan_block:
        lines.append(orphan_block)

    lines.append(cocos_body)
    lines.append(gd_body)

    lines.append(cocos_factory_text)
    lines.append(gd_factory_text)
    lines.append(geode_factory_text)

    lines.append("export type GeodeNamespace = {\n")
    lines.append("    cocos2d: Cocos2dNamespace,\n")
    lines.append("    gd: GDNamespace,\n")
    lines.append("    Mod: ModNamespace,\n")
    lines.append("    json: JsonNamespace,\n")
    lines.append("    fs: FsNamespace,\n")
    lines.append("    KeyboardInputEvent: KeyboardInputEventNamespace,\n")
    geode_enum_fields = enum_namespace_field_lines(plan.ctx.geode_enum_members)
    geode_namespace_fields = sorted(
        _factory_field_lines(geode_factories) + geode_enum_fields,
        key=lambda line: line.strip().split(":", 1)[0].strip(),
    )
    lines.extend(geode_namespace_fields)
    lines.extend(function_field_lines)
    lines.append("    hook: (target: string, callback: HookCallbackTable) -> HookHandle,\n")
    lines.append("    skip: (value: any?) -> any,\n")
    lines.append("    fields: (self: CCNode) -> { [string]: any },\n")
    lines.append("}\n\n")
    lines.append("declare geode: GeodeNamespace\n")

    content = "".join(lines)
    extra_dluau = _collect_extra_dluau()
    if extra_dluau:
        content += extra_dluau
    return {TYPES_FILE: content}
