from __future__ import annotations

import os
from typing import Dict, List, Tuple

from luau_codegen.parse.broma import Root
from luau_codegen.model.domain import lua_namespace
from luau_codegen.emit.plan import EmitPlan, collect_plan
from luau_codegen.emit.luau_types.classes import (
    _emit_class,
    _emitted_base_name,
    _should_emit_type_class,
    _topo_sort_chunks,
)
from luau_codegen.emit.luau_types.enums import _enum_block
from luau_codegen.emit.luau_types.factories import (
    _collect_factories,
    _emit_factories,
    _emit_factory_records,
    _factory_field_lines,
)
from luau_codegen.emit.luau_types.free_fn_tree import (
    _build_function_tree,
    _emit_function_tree,
)
from luau_codegen.emit.luau_types.references import (
    _VALUE_STUB_BODY,
    _emit_delegate_stub_block,
    _emit_orphan_stubs,
    _emit_value_stub_block,
    _factory_object_refs,
    _refs_from_classes,
    _refs_from_text,
    _value_refs_in_text,
)

TYPES_FILE = "geode.d.luau"
cocos_namespace = "geode.cocos2d"
gd_namespace = "geode.gd"
geode_namespace = "geode"

__all__ = ["emit", "TYPES_FILE"]

_PACKAGE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


def _collect_extra_dluau() -> str:
    extra_dir = os.path.join(_PACKAGE_DIR, "extra_bindings")
    if not os.path.isdir(extra_dir):
        return ""
    parts: list[str] = []
    for name in sorted(os.listdir(extra_dir)):
        if name.endswith(".dluau"):
            with open(os.path.join(extra_dir, name), "r", encoding="utf-8") as f:
                parts.append(f.read().strip())
    if not parts:
        return ""
    body = "\n\n".join(parts)
    return "\n\n-- Custom definitions from tools/luau_codegen/extra_bindings/\n" + body + "\n"


def _header(label: str) -> List[str]:
    return [
        "-- Generated by LuauAPI codegen\n",
        f"-- {label}\n",
        "\n",
    ]


def emit(
    root: Root,
    target_platform: str = "win",
    plan: EmitPlan | None = None,
    manual_fields: Dict[str, list] | None = None,
) -> Dict[str, str]:
    if plan is None:
        plan = collect_plan(root, target_platform)
    classes = plan.classes
    objects = plan.objects
    grouped_by_class = plan.supported_by_class
    skipped_classes = plan.skipped_classes

    cocos_chunks: List[Tuple[str, str]] = []
    gd_chunks: List[Tuple[str, str]] = []
    for cls in classes:
        field_targets = plan.field_targets_by_class.get(cls.name, [])
        if not _should_emit_type_class(
            cls,
            objects,
            field_targets,
            skipped_classes,
            target_platform=target_platform,
            ctx=plan.ctx,
        ):
            continue
        grouped = grouped_by_class[cls.name]
        chunk = "".join(
            _emit_class(
                cls,
                grouped,
                field_targets,
                objects,
                skipped_classes,
                target_platform=target_platform,
                ctx=plan.ctx,
            )
        )
        if lua_namespace(cls) == cocos_namespace:
            cocos_chunks.append((cls.name, chunk))
        else:
            gd_chunks.append((cls.name, chunk))

    base_of = {
        name: _emitted_base_name(objects[name], objects, skipped_classes)
        for name in {n for n, _ in cocos_chunks} | {n for n, _ in gd_chunks}
        if name in objects
    }
    cocos_chunks = _topo_sort_chunks(cocos_chunks, base_of)
    gd_chunks = _topo_sort_chunks(gd_chunks, base_of)

    cocos_body = "".join(chunk for _, chunk in cocos_chunks)
    gd_body = "".join(chunk for _, chunk in gd_chunks)

    cocos_factories = _collect_factories(
        classes, grouped_by_class, skipped_classes, cocos_namespace
    )
    gd_factories = _collect_factories(classes, grouped_by_class, skipped_classes, gd_namespace)
    geode_factories = _collect_factories(
        classes, grouped_by_class, skipped_classes, geode_namespace
    )
    cocos_factory_text = "".join(
        _emit_factories(cocos_factories, objects, cocos_namespace, ctx=plan.ctx)
    )
    gd_factory_text = "".join(_emit_factories(gd_factories, objects, gd_namespace, ctx=plan.ctx))

    geode_factory_text = "".join(_emit_factory_records(geode_factories, objects, ctx=plan.ctx))

    function_tree = _build_function_tree(plan.supported_free_functions, objects, manual_fields)
    function_field_lines = _emit_function_tree(function_tree, objects, 1, ctx=plan.ctx)

    defined = {name for name, _ in cocos_chunks} | {name for name, _ in gd_chunks}
    refs = _refs_from_classes(defined, grouped_by_class, objects, skipped_classes, ctx=plan.ctx)
    refs |= _factory_object_refs(cocos_factories, objects, ctx=plan.ctx)
    refs |= _factory_object_refs(gd_factories, objects, ctx=plan.ctx)
    refs |= _factory_object_refs(geode_factories, objects, ctx=plan.ctx)
    refs |= _refs_from_text(
        cocos_body + gd_body + cocos_factory_text + gd_factory_text + geode_factory_text
    )
    refs |= _refs_from_text("".join(function_field_lines))
    orphan_names = {
        name
        for name in refs
        if name not in defined and name in objects and name not in _VALUE_STUB_BODY
    }

    lines = _header("Geode type stubs")

    delegate_block = _emit_delegate_stub_block()
    value_block = _emit_value_stub_block(
        _value_refs_in_text(
            cocos_body + gd_body + cocos_factory_text + gd_factory_text + delegate_block
        )
    )
    if value_block:
        lines.append(value_block)
        lines.append("\n")

    if delegate_block:
        lines.append(delegate_block)
        lines.append("\n")

    for namespace in (cocos_namespace, gd_namespace, geode_namespace):
        enum_block = _enum_block(namespace, plan.ctx)
        if enum_block:
            lines.append(enum_block)
            lines.append("\n")

    orphan_block = _emit_orphan_stubs(orphan_names)
    if orphan_block:
        lines.append(orphan_block)

    lines.append(cocos_body)
    lines.append(gd_body)

    lines.append(cocos_factory_text)
    lines.append(gd_factory_text)
    lines.append(geode_factory_text)

    lines.append("export type HookHandle = {\n")
    lines.append("    enable: (self: HookHandle) -> (boolean, string?),\n")
    lines.append("    disable: (self: HookHandle) -> (boolean, string?),\n")
    lines.append("    remove: (self: HookHandle) -> boolean,\n")
    lines.append("    isEnabled: (self: HookHandle) -> boolean,\n")
    lines.append("}\n\n")
    lines.append("export type HookCallbackTable = {\n")
    lines.append("    before: ((...any) -> any?)?,\n")
    lines.append("    after: ((...any) -> any?)?,\n")
    lines.append("    priority: number?,\n")
    lines.append("}\n\n")

    lines.append("export type ModNamespace = {\n")
    lines.append("    getSavedValue: (key: string) -> any,\n")
    lines.append("    setSavedValue: (key: string, value: any) -> (),\n")
    lines.append("    getSettingValue: (key: string) -> any,\n")
    lines.append("    hasSetting: (key: string) -> boolean,\n")
    lines.append(
        "    listenForSettingChanges: (key: string, callback: (value: any) -> ()) -> (),\n"
    )
    lines.append(
        "    listenForAllSettingChanges: (callback: (key: string, value: any) -> ()) -> (),\n"
    )
    lines.append("    getID: () -> string,\n")
    lines.append("    getName: () -> string,\n")
    lines.append("    getVersion: () -> string,\n")
    lines.append("    getResourcesDir: () -> string,\n")
    lines.append("    getSaveDir: () -> string,\n")
    lines.append("    getConfigDir: () -> string,\n")
    lines.append("}\n\n")

    lines.append("export type JsonNamespace = {\n")
    lines.append("    parse: (text: string) -> (any?, string?),\n")
    lines.append("    dump: (value: any, indent: number?) -> string,\n")
    lines.append("}\n\n")

    lines.append('export type FsRoot = "save" | "config" | "persistent" | "resources"\n')
    lines.append("export type FsNamespace = {\n")
    lines.append("    read: (root: FsRoot, path: string) -> (string?, string?),\n")
    lines.append("    write: (root: FsRoot, path: string, data: string) -> (boolean?, string?),\n")
    lines.append("    exists: (root: FsRoot, path: string) -> (boolean?, string?),\n")
    lines.append("    list: (root: FsRoot, path: string) -> ({ string }?, string?),\n")
    lines.append("    mkdir: (root: FsRoot, path: string) -> (boolean?, string?),\n")
    lines.append("    remove: (root: FsRoot, path: string) -> (boolean?, string?),\n")
    lines.append("}\n\n")

    lines.append("export type ProxyOpts = {\n")
    lines.append("    address: string,\n")
    lines.append("    port: number?,\n")
    lines.append("    type: number?,\n")
    lines.append("    auth: number?,\n")
    lines.append("    username: string?,\n")
    lines.append("    password: string?,\n")
    lines.append("    tunneling: boolean?,\n")
    lines.append("    certVerification: boolean?,\n")
    lines.append("}\n\n")
    lines.append("export type RequestTimings = {\n")
    lines.append("    queueWait: number,\n")
    lines.append("    nameLookup: number,\n")
    lines.append("    connect: number,\n")
    lines.append("    tlsHandshake: number,\n")
    lines.append("    requestSend: number,\n")
    lines.append("    firstByte: number,\n")
    lines.append("    download: number,\n")
    lines.append("    total: number,\n")
    lines.append("}\n\n")
    lines.append("export type WebProgress = {\n")
    lines.append("    downloaded: number,\n")
    lines.append("    downloadTotal: number,\n")
    lines.append("    downloadProgress: number?,\n")
    lines.append("    uploaded: number,\n")
    lines.append("    uploadTotal: number,\n")
    lines.append("    uploadProgress: number?,\n")
    lines.append("}\n\n")
    lines.append("export type RequestOptions = {\n")
    lines.append("    url: string?,\n")
    lines.append("    method: string?,\n")
    lines.append("    headers: { [string]: string }?,\n")
    lines.append("    params: { [string]: string }?,\n")
    lines.append("    userAgent: string?,\n")
    lines.append("    acceptEncoding: string?,\n")
    lines.append("    timeout: number?,\n")
    lines.append("    downloadRange: { number }?,\n")
    lines.append("    certVerification: boolean?,\n")
    lines.append("    transferBody: boolean?,\n")
    lines.append("    followRedirects: boolean?,\n")
    lines.append("    ignoreContentLength: boolean?,\n")
    lines.append("    caBundle: string?,\n")
    lines.append("    proxy: ProxyOpts?,\n")
    lines.append("    version: number?,\n")
    lines.append("    body: string?,\n")
    lines.append("    bodyString: string?,\n")
    lines.append("    bodyJson: any?,\n")
    lines.append("    bodyMultipart: MultipartForm?,\n")
    lines.append("    onProgress: ((progress: WebProgress) -> ())?,\n")
    lines.append("}\n\n")
    lines.append("export type MultipartForm = {\n")
    lines.append(
        "    param: (self: MultipartForm, name: string, value: string) -> MultipartForm,\n"
    )
    lines.append(
        "    file: (self: MultipartForm, name: string, data: string, filename: string, mime: string?) -> MultipartForm,\n"
    )
    lines.append(
        "    fileFrom: (self: MultipartForm, name: string, root: FsRoot, path: string, mime: string?) -> (MultipartForm?, string?),\n"
    )
    lines.append("    getBoundary: (self: MultipartForm) -> string,\n")
    lines.append("    getHeader: (self: MultipartForm) -> string,\n")
    lines.append("    getBody: (self: MultipartForm) -> string,\n")
    lines.append("}\n\n")
    lines.append("export type WebResponse = {\n")
    lines.append("    info: (self: WebResponse) -> boolean,\n")
    lines.append("    ok: (self: WebResponse) -> boolean,\n")
    lines.append("    redirected: (self: WebResponse) -> boolean,\n")
    lines.append("    badClient: (self: WebResponse) -> boolean,\n")
    lines.append("    badServer: (self: WebResponse) -> boolean,\n")
    lines.append("    error: (self: WebResponse) -> boolean,\n")
    lines.append("    cancelled: (self: WebResponse) -> boolean,\n")
    lines.append("    code: (self: WebResponse) -> number,\n")
    lines.append("    text: (self: WebResponse) -> (string?, string?),\n")
    lines.append("    json: (self: WebResponse) -> (any?, string?),\n")
    lines.append("    bytes: (self: WebResponse) -> string,\n")
    lines.append(
        "    saveTo: (self: WebResponse, root: FsRoot, path: string) -> (boolean?, string?),\n"
    )
    lines.append("    headers: (self: WebResponse) -> { string },\n")
    lines.append("    header: (self: WebResponse, name: string) -> string?,\n")
    lines.append("    headersNamed: (self: WebResponse, name: string) -> { string }?,\n")
    lines.append("    errorMessage: (self: WebResponse) -> string,\n")
    lines.append("    verboseLogs: (self: WebResponse) -> string,\n")
    lines.append("    timings: (self: WebResponse) -> RequestTimings,\n")
    lines.append("}\n\n")
    lines.append("export type WebHandle = {\n")
    lines.append("    cancel: (self: WebHandle) -> boolean,\n")
    lines.append("    id: (self: WebHandle) -> number?,\n")
    lines.append("}\n\n")
    lines.append("export type WebRequest = {\n")
    lines.append("    header: (self: WebRequest, name: string, value: string) -> WebRequest,\n")
    lines.append("    removeHeader: (self: WebRequest, name: string) -> WebRequest,\n")
    lines.append("    param: (self: WebRequest, name: string, value: string) -> WebRequest,\n")
    lines.append("    removeParam: (self: WebRequest, name: string) -> WebRequest,\n")
    lines.append("    method: (self: WebRequest, method: string) -> WebRequest,\n")
    lines.append("    url: (self: WebRequest, url: string) -> WebRequest,\n")
    lines.append("    userAgent: (self: WebRequest, name: string) -> WebRequest,\n")
    lines.append("    acceptEncoding: (self: WebRequest, encoding: string) -> WebRequest,\n")
    lines.append("    timeout: (self: WebRequest, seconds: number) -> WebRequest,\n")
    lines.append(
        "    downloadRange: (self: WebRequest, start: number, stop: number) -> WebRequest,\n"
    )
    lines.append("    certVerification: (self: WebRequest, enabled: boolean) -> WebRequest,\n")
    lines.append("    transferBody: (self: WebRequest, enabled: boolean) -> WebRequest,\n")
    lines.append("    followRedirects: (self: WebRequest, enabled: boolean) -> WebRequest,\n")
    lines.append("    ignoreContentLength: (self: WebRequest, enabled: boolean) -> WebRequest,\n")
    lines.append("    caBundle: (self: WebRequest, content: string) -> WebRequest,\n")
    lines.append("    proxy: (self: WebRequest, opts: ProxyOpts) -> WebRequest,\n")
    lines.append("    version: (self: WebRequest, version: number) -> WebRequest,\n")
    lines.append("    body: (self: WebRequest, data: string) -> WebRequest,\n")
    lines.append("    bodyString: (self: WebRequest, data: string) -> WebRequest,\n")
    lines.append("    bodyJson: (self: WebRequest, value: any) -> WebRequest,\n")
    lines.append("    bodyMultipart: (self: WebRequest, form: MultipartForm) -> WebRequest,\n")
    lines.append(
        "    onProgress: (self: WebRequest, callback: (progress: WebProgress) -> ()) -> WebRequest,\n"
    )
    lines.append(
        "    send: ((self: WebRequest, method: string, url: string, callback: (response: WebResponse) -> ()) -> WebHandle) & ((self: WebRequest, method: string, url: string, options: RequestOptions, callback: (response: WebResponse) -> ()) -> WebHandle),\n"
    )
    lines.append(
        "    get: ((self: WebRequest, url: string, callback: (response: WebResponse) -> ()) -> WebHandle) & ((self: WebRequest, url: string, options: RequestOptions, callback: (response: WebResponse) -> ()) -> WebHandle),\n"
    )
    lines.append(
        "    post: ((self: WebRequest, url: string, callback: (response: WebResponse) -> ()) -> WebHandle) & ((self: WebRequest, url: string, options: RequestOptions, callback: (response: WebResponse) -> ()) -> WebHandle),\n"
    )
    lines.append(
        "    put: ((self: WebRequest, url: string, callback: (response: WebResponse) -> ()) -> WebHandle) & ((self: WebRequest, url: string, options: RequestOptions, callback: (response: WebResponse) -> ()) -> WebHandle),\n"
    )
    lines.append(
        "    patch: ((self: WebRequest, url: string, callback: (response: WebResponse) -> ()) -> WebHandle) & ((self: WebRequest, url: string, options: RequestOptions, callback: (response: WebResponse) -> ()) -> WebHandle),\n"
    )
    lines.append("    getID: (self: WebRequest) -> number,\n")
    lines.append("    getMethod: (self: WebRequest) -> string,\n")
    lines.append("    getUrl: (self: WebRequest) -> string,\n")
    lines.append("    getHeaders: (self: WebRequest) -> { [string]: { string } },\n")
    lines.append("    getUrlParams: (self: WebRequest) -> { [string]: string },\n")
    lines.append("    getBody: (self: WebRequest) -> string?,\n")
    lines.append("    getTimeout: (self: WebRequest) -> number?,\n")
    lines.append("    getVersion: (self: WebRequest) -> number,\n")
    lines.append("    getProgress: (self: WebRequest) -> WebProgress,\n")
    lines.append("}\n\n")
    lines.append("export type WebListenerHandle = {\n")
    lines.append("    disconnect: (self: WebListenerHandle) -> (),\n")
    lines.append("}\n\n")
    lines.append("export type WebNamespace = {\n")
    lines.append("    openLinkInBrowser: (url: string) -> (),\n")
    lines.append("    newRequest: () -> WebRequest,\n")
    lines.append("    multipart: () -> MultipartForm,\n")
    lines.append(
        "    get: ((url: string, callback: (response: WebResponse) -> ()) -> WebHandle) & ((url: string, options: RequestOptions, callback: (response: WebResponse) -> ()) -> WebHandle),\n"
    )
    lines.append(
        "    post: ((url: string, callback: (response: WebResponse) -> ()) -> WebHandle) & ((url: string, options: RequestOptions, callback: (response: WebResponse) -> ()) -> WebHandle),\n"
    )
    lines.append(
        "    put: ((url: string, callback: (response: WebResponse) -> ()) -> WebHandle) & ((url: string, options: RequestOptions, callback: (response: WebResponse) -> ()) -> WebHandle),\n"
    )
    lines.append(
        "    patch: ((url: string, callback: (response: WebResponse) -> ()) -> WebHandle) & ((url: string, options: RequestOptions, callback: (response: WebResponse) -> ()) -> WebHandle),\n"
    )
    lines.append(
        "    fetch: ((url: string, callback: (response: WebResponse) -> ()) -> WebHandle) & ((url: string, options: RequestOptions, callback: (response: WebResponse) -> ()) -> WebHandle) & ((options: RequestOptions, callback: (response: WebResponse) -> ()) -> WebHandle),\n"
    )
    lines.append(
        "    onRequestIntercept: (callback: (modID: string, request: WebRequest) -> boolean?, priority: number?) -> WebListenerHandle,\n"
    )
    lines.append(
        "    onRequestInterceptFor: (modID: string, callback: (request: WebRequest) -> boolean?, priority: number?) -> WebListenerHandle,\n"
    )
    lines.append(
        "    onRequestInterceptById: (requestID: number, callback: (request: WebRequest) -> boolean?, priority: number?) -> WebListenerHandle,\n"
    )
    lines.append(
        "    onResponse: (callback: (modID: string, response: WebResponse) -> boolean?, priority: number?) -> WebListenerHandle,\n"
    )
    lines.append(
        "    onResponseFor: (modID: string, callback: (response: WebResponse) -> boolean?, priority: number?) -> WebListenerHandle,\n"
    )
    lines.append(
        "    onResponseById: (requestID: number, callback: (response: WebResponse) -> boolean?, priority: number?) -> WebListenerHandle,\n"
    )
    lines.append(
        "    HttpVersion: { DEFAULT: number, VERSION_1_0: number, VERSION_1_1: number, VERSION_2_0: number, VERSION_2TLS: number, VERSION_2_PRIOR_KNOWLEDGE: number, VERSION_3: number, VERSION_3ONLY: number },\n"
    )
    lines.append(
        "    ProxyType: { HTTP: number, HTTPS: number, HTTPS2: number, SOCKS4: number, SOCKS4A: number, SOCKS5: number, SOCKS5H: number },\n"
    )
    lines.append(
        "    Error: { CURL_INITIALIZATION_ERROR: number, REQUEST_CANCELLED: number, QUEUE_FULL: number, CHANNEL_CLOSED: number },\n"
    )
    lines.append(
        "    HttpAuth: { BASIC: number, DIGEST: number, DIGEST_IE: number, BEARER: number, NEGOTIATE: number, NTLM: number, NTLM_WB: number, ANY: number, ANYSAFE: number, ONLY: number, AWS_SIGV4: number },\n"
    )
    lines.append("}\n\n")

    lines.append("export type GeodeNamespace = {\n")
    lines.append("    cocos2d: Cocos2dNamespace,\n")
    lines.append("    gd: GDNamespace,\n")
    lines.append("    Mod: ModNamespace,\n")
    lines.append("    json: JsonNamespace,\n")
    lines.append("    fs: FsNamespace,\n")
    lines.extend(_factory_field_lines(geode_factories))
    lines.extend(function_field_lines)
    lines.append("    hook: (target: string, callback: HookCallbackTable) -> HookHandle,\n")
    lines.append("    skip: (value: any?) -> any,\n")
    lines.append("    fields: (self: CCNode) -> { [string]: any },\n")
    lines.append("}\n\n")
    lines.append("declare geode: GeodeNamespace\n")

    content = "".join(lines)
    extra_dluau = _collect_extra_dluau()
    if extra_dluau:
        content += extra_dluau
    return {TYPES_FILE: content}
