from __future__ import annotations


def file_preamble() -> str:
    return (
        "// Generated by LuauAPI codegen\n\n"
        '#include "lua/Runtime.hpp"\n'
        '#include "lua/Binding.hpp"\n'
        '#include "lua/bindings/internal/LuaRef.hpp"\n'
        '#include "lua/bindings/internal/Stack.hpp"\n'
        '#include "lua/bindings/internal/TableUtil.hpp"\n'
        '#include "lua/bindings/internal/Types.hpp"\n'
        '#include "lua/bindings/internal/Usertype.hpp"\n\n'
        "#include <Geode/Geode.hpp>\n"
        "#include <Geode/loader/Hook.hpp>\n"
        "#include <Geode/loader/Mod.hpp>\n"
        "#include <Geode/loader/Tulip.hpp>\n"
        "#include <cocos2d.h>\n"
        "#include <lua.h>\n\n"
        "#include <cstddef>\n"
        "#include <memory>\n"
        "#include <string>\n"
        "#include <string_view>\n"
        "#include <unordered_map>\n"
        "#include <vector>\n\n"
    )


def emit_internal_hpp() -> str:
    return (
        "// Generated by LuauAPI codegen\n\n"
        "#pragma once\n\n"
        '#include "lua/Runtime.hpp"\n'
        '#include "lua/bindings/internal/LuaRef.hpp"\n\n'
        "#include <Geode/Geode.hpp>\n"
        "#include <Geode/loader/Hook.hpp>\n\n"
        "#include <cstddef>\n"
        "#include <memory>\n"
        "#include <string>\n"
        "#include <unordered_map>\n"
        "#include <vector>\n\n"
        "namespace luauapi_gen {\n"
        "using CreateHookFn = geode::Result<geode::Hook*>(*)(std::string const&);\n\n"
        "struct LuaHookTarget {\n"
        "    char const* id;\n"
        "    char const* displayName;\n"
        "    CreateHookFn createHook;\n"
        "};\n\n"
        "struct LuaHookCallback {\n"
        "    std::size_t id = 0;\n"
        "    luax::LuaRef ref;\n"
        "    bool removed = false;\n"
        "};\n\n"
        "struct LuaHookState {\n"
        "    LuaHookTarget const* target = nullptr;\n"
        "    geode::Hook* hook = nullptr;\n"
        "    std::vector<std::shared_ptr<LuaHookCallback>> callbacks;\n"
        "};\n\n"
        "std::unordered_map<std::string, LuaHookState>& hookStates();\n\n"
        "template <class PushContext, class ApplyReturn>\n"
        "void runLuaPostHooks(char const* targetId, int nargs, PushContext pushContext, ApplyReturn applyReturn) {\n"
        "    auto it = hookStates().find(targetId);\n"
        "    if (it == hookStates().end()) return;\n"
        "    auto callbacks = it->second.callbacks;\n"
        "    auto* runtime = luax::Runtime::getIfInitialized();\n"
        "    if (!runtime || !runtime->ready()) return;\n"
        "    auto* L = runtime->state();\n"
        "    if (!L) return;\n"
        "    for (auto const& callback : callbacks) {\n"
        "        if (!callback || callback->removed || !callback->ref.valid()) continue;\n"
        "        int top = lua_gettop(L);\n"
        "        if (!callback->ref.push()) {\n"
        "            lua_settop(L, top);\n"
        "            continue;\n"
        "        }\n"
        "        pushContext(L);\n"
        "        luax::Runtime::ResourcesRootScope rootScope(*runtime, callback->ref.resourcesRoot());\n"
        "        if (runtime->protectedCall(nargs, 1, targetId, 50)) {\n"
        "            if (!lua_isnil(L, -1) && !applyReturn(L, -1)) {\n"
        '                geode::log::warn("luau hook [{}] returned invalid override", targetId);\n'
        "            }\n"
        "        }\n"
        "        lua_settop(L, top);\n"
        "    }\n"
        "}\n"
        "} // namespace luauapi_gen\n"
    )
