from __future__ import annotations

# Manually maintained, you can try removing some but it will probably break.

INACCESSIBLE_METHODS = {
    ("CCActionManager", "update"),
    ("CCAnimationCache", "parseVersion1"),
    ("CCAnimationCache", "parseVersion2"),
    ("CCAtlasNode", "calculateMaxItems"),
    ("CCAtlasNode", "setIgnoreContentScaleFactor"),
    ("CCAtlasNode", "updateBlendFunc"),
    ("CCAtlasNode", "updateOpacityModifyRGB"),
    ("CCBMFontConfiguration", "parseCommonArguments"),
    ("CCBMFontConfiguration", "parseImageFileName"),
    ("CCBMFontConfiguration", "parseInfoArguments"),
    ("CCBMFontConfiguration", "parseKerningEntry"),
    ("CCBMFontConfiguration", "purgeFontDefDictionary"),
    ("CCBMFontConfiguration", "purgeKerningDictionary"),
    (
        "CCControlPotentiometer",
        "angleInDegreesBetweenLineFromPoint_toPoint_toLineFromPoint_toPoint",
    ),
    ("CCControl", "create"),
    # ("CCControlButton", "doesAdjustBackgroundImage"),
    # ("CCControlButton", "getColor"),
    # ("CCControlButton", "getOpacity"),
    # ("CCControlButton", "setAdjustBackgroundImage"),
    # ("CCControlButton", "setColor"),
    # ("CCControlButton", "setOpacity"),
    ("CCControlColourPicker", "updateControlPicker"),
    ("CCControlColourPicker", "updateHueAndControlPicker"),
    ("CCControlHuePicker", "checkSliderPosition"),
    # ("CCControlHuePicker", "setHue"),
    # ("CCControlHuePicker", "setHuePercentage"),
    ("CCControlHuePicker", "updateSliderPosition"),
    ("CCControlPotentiometer", "distanceBetweenPointAndPoint"),
    ("CCControlPotentiometer", "potentiometerBegan"),
    ("CCControlPotentiometer", "potentiometerEnded"),
    ("CCControlPotentiometer", "potentiometerMoved"),
    ("CCControlSaturationBrightnessPicker", "checkSliderPosition"),
    ("CCControlSaturationBrightnessPicker", "updateSliderPosition"),
    # ("CCControlSlider", "isTouchInside"),
    # ("CCControlSlider", "locationFromTouch"),
    # ("CCControlSlider", "setEnabled"),
    # ("CCControlSlider", "setMaximumValue"),
    # ("CCControlSlider", "setMinimumValue"),
    # ("CCControlSlider", "setValue"),
    ("CCControlSlider", "sliderBegan"),
    ("CCControlSlider", "sliderEnded"),
    ("CCControlSlider", "sliderMoved"),
    ("CCControlSlider", "valueForLocation"),
    # ("CCControlStepper", "startAutorepeat"),
    # ("CCControlStepper", "stopAutorepeat"),
    # ("CCControlStepper", "updateLayoutUsingTouchLocation"),
    ("CCDictionary", "setObjectUnSafe"),
    ("CCDirector", "calculateDeltaTime"),
    ("CCDirector", "calculateMPF"),
    ("CCDirector", "createStatsLabel"),
    ("CCDirector", "purgeDirector"),
    ("CCDirector", "setNextScene"),
    ("CCDirector", "showStats"),
    ("CCDrawNode", "ensureCapacity"),
    ("CCDrawNode", "render"),
    ("CCGLProgram", "description"),
    # ("CCLabelTTF", "canAttachWithIME"),
    # ("CCLabelTTF", "canDetachWithIME"),
    # ("CCLabelTTF", "deleteBackward"),
    # ("CCLabelTTF", "deleteForward"),
    # ("CCLabelTTF", "draw"),
    # ("CCLabelTTF", "getContentText"),
    ("CCLabelTTF", "updateTexture"),
    ("CCLayer", "excuteScriptTouchHandler"),
    ("CCLayerColor", "updateColor"),
    ("CCLabelBMFont", "getLetterPosXLeft"),
    ("CCLabelBMFont", "getLetterPosXRight"),
    ("CCLabelBMFont", "kerningAmountForFirst"),
    ("CCMenu", "itemForTouch"),
    ("CCMenuItemFont", "recreateLabel"),
    ("CCMenuItemSprite", "updateImagesVisibility"),
    ("CCNode", "childrenAlloc"),
    ("CCNode", "convertToWindowSpace"),
    ("CCNode", "detachChild"),
    ("CCNode", "insertChild"),
    ("CCNode", "resetGlobalOrderOfArrival"),
    ("CCNotificationCenter", "observerExisted"),
    ("CCParallaxNode", "absolutePosition"),
    ("CCParticleBatchNode", "addChildHelper"),
    ("CCParticleBatchNode", "increaseAtlasCapacityTo"),
    ("CCParticleBatchNode", "searchNewPositionInChildrenForZ"),
    ("CCParticleBatchNode", "updateAllAtlasIndexes"),
    ("CCParticleBatchNode", "updateBlendFunc"),
    ("CCParticleSystem", "updateBlendFunc"),
    ("CCParticleSystemQuad", "allocMemory"),
    ("CCParticleSystemQuad", "setupVBO"),
    ("CCParticleSystemQuad", "setupVBOandVAO"),
    ("CCProgressTimer", "boundaryTexCoord"),
    ("CCProgressTimer", "updateBar"),
    ("CCProgressTimer", "updateColor"),
    ("CCProgressTimer", "updateProgress"),
    ("CCProgressTimer", "updateRadial"),
    ("CCRenderTexture", "beginWithClear"),
    ("CCScale9Sprite", "updateCapInset"),
    ("CCScale9Sprite", "updatePositions"),
    # ("CCScriptHandlerEntry", "create"),
    # ("CCSchedulerScriptHandlerEntry", "create"),
    # ("CCSchedulerScriptHandlerEntry", "init"),
    ("CCScrollView", "afterDraw"),
    ("CCScrollView", "beforeDraw"),
    ("CCScrollView", "deaccelerateScrolling"),
    ("CCScrollView", "getViewRect"),
    ("CCScrollView", "performedAnimatedScroll"),
    ("CCScrollView", "relocateContainer"),
    ("CCScrollView", "stoppedAnimatedScroll"),
    ("CCScheduler", "scheduleScriptFunc"),
    ("CCScheduler", "unscheduleScriptEntry"),
    ("CCShaderCache", "init"),
    ("CCShaderCache", "loadDefaultShader"),
    ("CCSprite", "setDirtyRecursively"),
    ("CCSprite", "setReorderChildDirtyRecursively"),
    ("CCSprite", "setTextureCoords"),
    ("CCSprite", "updateBlendFunc"),
    ("CCSprite", "updateColor"),
    ("CCSpriteBatchNode", "addSpriteWithoutQuad"),
    ("CCSpriteBatchNode", "insertQuadFromSprite"),
    ("CCSpriteBatchNode", "swap"),
    ("CCSpriteBatchNode", "updateBlendFunc"),
    ("CCSpriteBatchNode", "updateQuadFromSprite"),
    ("CCSpriteFrameCache", "addSpriteFramesWithDictionary"),
    ("CCSpriteFrameCache", "removeSpriteFramesFromDictionary"),
    # ("CCSplitRows", "initWithDuration"),
    # ("CCSplitRows", "startWithTarget"),
    # ("CCSplitRows", "update"),
    ("CCTMXLayer", "appendTileForGID"),
    ("CCTMXLayer", "atlasIndexForExistantZ"),
    ("CCTMXLayer", "atlasIndexForNewZ"),
    ("CCTMXLayer", "calculateLayerOffset"),
    ("CCTMXLayer", "insertTileForGID"),
    ("CCTMXLayer", "parseInternalProperties"),
    ("CCTMXLayer", "positionForHexAt"),
    ("CCTMXLayer", "positionForIsoAt"),
    ("CCTMXLayer", "positionForOrthoAt"),
    ("CCTMXLayer", "reusedTileWithRect"),
    ("CCTMXLayer", "setupTileSprite"),
    ("CCTMXLayer", "updateTileForGID"),
    ("CCTMXLayer", "vertexZForPos"),
    ("CCTMXMapInfo", "internalInit"),
    ("CCTMXTiledMap", "buildWithMapInfo"),
    ("CCTMXTiledMap", "parseLayer"),
    ("CCTMXTiledMap", "tilesetForLayer"),
    ("CCTableView", "__indexFromOffset"),
    ("CCTableView", "__offsetFromIndex"),
    ("CCTableView", "_addCellIfNecessary"),
    ("CCTableView", "_indexFromOffset"),
    ("CCTableView", "_moveCellOutOfSight"),
    ("CCTableView", "_offsetFromIndex"),
    ("CCTableView", "_setIndexForCell"),
    ("CCTableView", "_updateCellPositions"),
    ("CCTextFieldTTF", "canAttachWithIME"),
    ("CCTextFieldTTF", "canDetachWithIME"),
    ("CCTextFieldTTF", "deleteBackward"),
    ("CCTextFieldTTF", "deleteForward"),
    ("CCTextFieldTTF", "draw"),
    ("CCTextFieldTTF", "getContentText"),
    ("CCTextFieldTTF", "insertText"),
    ("CCTexture2D", "initPremultipliedATextureWithImage"),
    ("CCTextureAtlas", "fillWithEmptyQuadsFromIndex"),
    ("CCTextureAtlas", "mapBuffers"),
    ("CCTextureAtlas", "setupIndices"),
    ("CCTextureAtlas", "setupVBO"),
    ("CCTextureAtlas", "setupVBOandVAO"),
    ("CCTextureCache", "addImageAsyncCallBack"),
    ("CCTextureETC", "loadTexture"),
    # ("CCTexturePVR", "createGLTexture"),
    ("CCTileMapAtlas", "calculateItemsToRender"),
    ("CCTileMapAtlas", "loadTGAfile"),
    ("CCTileMapAtlas", "updateAtlasValueAt"),
    ("CCTileMapAtlas", "updateAtlasValues"),
    ("CCTouchDispatcher", "decrementForcePrio"),
    ("CCTouchDispatcher", "forceAddHandler"),
    ("CCTouchDispatcher", "forceRemoveAllDelegates"),
    # ("CCTouchDispatcher", "forceRemoveDelegate"),
    ("CCTouchDispatcher", "incrementForcePrio"),
    ("CCTouchDispatcher", "rearrangeHandlers"),
    # ("CCTouchScriptHandlerEntry", "create"),
    # ("CCTouchScriptHandlerEntry", "init"),
    # ("CCTransitionCrossFade", "draw"),
    # ("CCTransitionCrossFade", "onEnter"),
    # ("CCTransitionCrossFade", "onExit"),
    ("CCTransitionFadeTR", "sceneOrder"),
    ("CCTransitionPageTurn", "sceneOrder"),
    ("CCTransitionProgress", "progressTimerNodeWithRenderTexture"),
    ("CCTransitionProgress", "sceneOrder"),
    ("CCTransitionProgress", "setupTransition"),
    ("CCTransitionProgressHorizontal", "progressTimerNodeWithRenderTexture"),
    ("CCTransitionProgressInOut", "progressTimerNodeWithRenderTexture"),
    ("CCTransitionProgressInOut", "sceneOrder"),
    ("CCTransitionProgressInOut", "setupTransition"),
    ("CCTransitionProgressOutIn", "progressTimerNodeWithRenderTexture"),
    ("CCTransitionProgressRadialCCW", "progressTimerNodeWithRenderTexture"),
    ("CCTransitionProgressRadialCW", "progressTimerNodeWithRenderTexture"),
    ("CCTransitionProgressVertical", "progressTimerNodeWithRenderTexture"),
    ("CCTransitionScene", "sceneOrder"),
    ("CCTransitionScene", "setNewScene"),
    ("CCTransitionSlideInB", "sceneOrder"),
    ("CCTransitionSlideInL", "sceneOrder"),
    ("CCTransitionSlideInR", "sceneOrder"),
    ("CCTransitionSlideInT", "sceneOrder"),
    # ("CCTransitionTurnOffTiles", "easeActionWithAction"),
    # ("CCTransitionTurnOffTiles", "onEnter"),
    ("CCTransitionTurnOffTiles", "sceneOrder"),
    ("EditorUI", "onToggleTraceIn"),
    ("EditorUI", "onToggleTraceOut"),
    # ("GJBaseGameLayer", "checkSpawnAbuse"),
    # ("GJBaseGameLayer", "isButtonAllowed"),
    # ("GJOptionsLayer", "getToggleButton"),
    ("EnterEffectObject", "init"),
    ("GJTransformControl", "calculateRotationOffset"),
    ("GJTransformControl", "finishTouch"),
    ("GJTransformControl", "logCurrentZeroPos"),
    ("GJTransformControl", "spriteByTag"),
    ("GJTransformControl", "updateMinMaxPositions"),
    ("GameLevelManager", "hasLikedItemFullCheck"),
    # ("LevelSearchLayer", "onPasteClipboard"),
}

INACCESSIBLE_CLASSES = {
    "CCGrabber",
    "CCProfilingTimer",
    "CCSchedulerScriptHandlerEntry",
    "CCScriptHandlerEntry",
    "CCTexturePVR",
    "CCTouchScriptHandlerEntry",
}
