from __future__ import annotations

from collections import defaultdict
from typing import Dict, List, Sequence

from broma_parser import Class, Method, Root
from emit_luau_bindings import _group_supported, _linkless_class_names
from model import lua_namespace, object_classes, short_name
from type_map import TypeInfo, classify_arg, classify_return

LUAU_KEYWORDS = frozenset({
    "and", "break", "do", "else", "elseif", "end", "false", "for",
    "function", "if", "in", "local", "nil", "not", "or", "repeat",
    "return", "then", "true", "until", "while", "continue",
    "export", "type", "typeof", "declare",
})


def _ret(ret: TypeInfo) -> str:
    if ret.kind == "void":
        return "()"
    return ret.lua_type


def _fn(args: Sequence[TypeInfo], ret: TypeInfo, self_name: str | None = None) -> str:
    params = []
    if self_name:
        params.append(f"self: {self_name}")
    for i, arg in enumerate(args, start=1):
        params.append(f"arg{i}: {arg.lua_type}")
    return f"({', '.join(params)}) -> {_ret(ret)}"


def _classify_args(method: Method, objects: Dict[str, Class]) -> List[TypeInfo]:
    args: List[TypeInfo] = []
    for arg in method.args:
        info = classify_arg(arg.type, objects)
        assert info is not None
        args.append(info)
    return args


def _method_type(cls: Class, methods: List[Method], objects: Dict[str, Class]) -> str:
    parts = []
    for m in methods:
        args = _classify_args(m, objects)
        ret = classify_return(m.ret, objects)
        assert ret is not None
        parts.append(_fn(args, ret, None if m.is_static else cls.name))
    return " & ".join(f"({p})" for p in parts)


def _prelude() -> str:
    return """
export type RGBColor = { r: number, g: number, b: number }
export type CCSize = { width: number, height: number }
export type CCPoint = { x: number, y: number }
export type CCRect = { origin: CCPoint, size: CCSize }
"""


def emit(root: Root, target_platform: str = "win") -> str:
    classes = object_classes(root)
    objects = {cls.name: cls for cls in classes}
    objects.update({cls.qualified_name: cls for cls in classes})
    grouped_by_class: Dict[str, Dict[str, List[Method]]] = {}
    skipped_by_class: Dict[str, List[tuple[Method, str]]] = {}
    factories: Dict[str, Dict[str, List[Method]]] = defaultdict(dict)

    lines = [
        "-- Generated by LuauAPI codegen\n",
        "-- Source of truth: Geode Broma bindings\n\n",
    ]
    lines.append(_prelude())
    lines.append("\n")

    for cls in classes:
        grouped, cls_skipped = _group_supported(cls, objects, target_platform)
        grouped_by_class[cls.name] = grouped
        skipped_by_class[cls.name] = cls_skipped

    skipped_classes = _linkless_class_names(classes, objects, grouped_by_class, skipped_by_class, target_platform)

    for cls in classes:
        if cls.name in skipped_classes:
            continue
        grouped = grouped_by_class[cls.name]
        base = ""
        for b in cls.bases:
            b_cls = objects.get(short_name(b))
            if b_cls and b_cls.name not in skipped_classes:
                base = f" extends {b_cls.name}"
                break
        instance_methods = {k: v for k, v in grouped.items() if not v[0].is_static and k not in LUAU_KEYWORDS}
        if not instance_methods:
            lines.append(f"declare class {cls.name}{base} end\n\n")
        else:
            lines.append(f"declare class {cls.name}{base}\n")
            for name, methods in sorted(instance_methods.items()):
                if len(methods) == 1:
                    m = methods[0]
                    args = _classify_args(m, objects)
                    ret = classify_return(m.ret, objects)
                    assert ret is not None
                    arg_text = ", ".join(f"arg{i}: {arg.lua_type}" for i, arg in enumerate(args, start=1))
                    suffix = "" if ret.kind == "void" else f": {ret.lua_type}"
                    joiner = ", " if arg_text else ""
                    lines.append(f"    function {name}(self{joiner}{arg_text}){suffix}\n")
                else:
                    lines.append(f"    {name}: {_method_type(cls, methods, objects)}\n")
            lines.append("end\n\n")
        static_methods = {k: v for k, v in grouped.items() if v[0].is_static and k not in LUAU_KEYWORDS}
        if static_methods:
            factories[cls.name] = static_methods

    for cls_name, methods in sorted(factories.items()):
        lines.append(f"export type {cls_name}Factory = {{\n")
        if cls_name == "GameManager":
            lines.append("    get: () -> GameManager,\n")
        for name, overloads in sorted(methods.items()):
            lines.append(f"    {name}: {_method_type(objects[cls_name], overloads, objects)},\n")
        lines.append("}\n\n")

    cocos = []
    gd = []
    for cls in classes:
        if cls.name in skipped_classes:
            continue
        factory = f"{cls.name}Factory" if cls.name in factories else "{}"
        if lua_namespace(cls) == "geode.cocos2d":
            cocos.append((cls.name, factory))
        else:
            gd.append((cls.name, factory))

    lines.append("export type Cocos2dNamespace = {\n")
    for name, factory in sorted(cocos):
        lines.append(f"    {name}: {factory},\n")
    lines.append("}\n\n")

    lines.append("export type GDNamespace = {\n")
    for name, factory in sorted(gd):
        lines.append(f"    {name}: {factory},\n")
    lines.append("}\n\n")

    lines.append("export type GeodeNamespace = {\n")
    lines.append("    cocos2d: Cocos2dNamespace,\n")
    lines.append("    gd: GDNamespace,\n")
    lines.append("}\n\n")
    lines.append("declare geode: GeodeNamespace\n")
    return "".join(lines)
