from __future__ import annotations

from collections import defaultdict
from typing import Dict, List, Sequence

from broma_parser import Class, Method, Root
from filtering import group_supported, linkless_class_names, prune_skipped_class_refs
from model import codegen_object_map, lua_namespace, object_classes, short_name
from type_map import TypeInfo, classify_arg, classify_return, enum_lua_names

LUAU_KEYWORDS = frozenset(
    {
        "and",
        "break",
        "do",
        "else",
        "elseif",
        "end",
        "false",
        "for",
        "function",
        "if",
        "in",
        "local",
        "nil",
        "not",
        "or",
        "repeat",
        "return",
        "then",
        "true",
        "until",
        "while",
        "continue",
        "export",
        "type",
        "typeof",
        "declare",
    }
)


def _ret(ret: TypeInfo) -> str:
    if ret.kind == "void":
        return "()"
    return ret.lua_type


def _fn(args: Sequence[TypeInfo], ret: TypeInfo, self_name: str | None = None) -> str:
    params = []
    if self_name:
        params.append(f"self: {self_name}")
    for i, arg in enumerate(args, start=1):
        params.append(f"arg{i}: {arg.lua_type}")
    return f"({', '.join(params)}) -> {_ret(ret)}"


def _classify_args(method: Method, objects: Dict[str, Class]) -> List[TypeInfo]:
    args: List[TypeInfo] = []
    for arg in method.args:
        info = classify_arg(arg.type, objects)
        assert info is not None
        args.append(info)
    return args


def _method_return_type(cls: Class, m: Method, objects: Dict[str, Class]) -> str:
    ret = classify_return(m.ret, objects)
    assert ret is not None
    out_types: List[str] = []
    if ret.kind != "void":
        out_types.append(ret.lua_type)
    if ret.kind == "void":
        for arg in m.args:
            info = classify_arg(arg.type, objects)
            assert info is not None
            if info.is_out:
                out_types.append(info.lua_type)
    if not out_types:
        return "()"
    if len(out_types) == 1:
        return out_types[0]
    return "(" + ", ".join(out_types) + ")"


def _method_type(cls: Class, methods: List[Method], objects: Dict[str, Class]) -> str:
    parts = []
    for m in methods:
        args = _classify_input_args(m, objects)
        ret_type = _method_return_type(cls, m, objects)
        params = []
        if not m.is_static:
            params.append(f"self: {cls.name}")
        for i, arg in enumerate(args, start=1):
            params.append(f"arg{i}: {arg.lua_type}")
        parts.append(f"({', '.join(params)}) -> {ret_type}")
    return " & ".join(f"({p})" for p in parts)


def _classify_input_args(m: Method, objects: Dict[str, Class]) -> List[TypeInfo]:
    ret = classify_return(m.ret, objects)
    assert ret is not None
    args: List[TypeInfo] = []
    for arg in m.args:
        info = classify_arg(arg.type, objects)
        assert info is not None
        if ret.kind == "void" and info.is_out:
            continue
        args.append(info)
    return args


VALUE_TYPE_STUBS = """export type RGBColor = { r: number, g: number, b: number }
export type CCSize = { width: number, height: number }
export type CCPoint = { x: number, y: number }
export type CCRect = { origin: CCPoint, size: CCSize }
export type UIButtonConfig = {
    width: number,
    height: number,
    deadzone: number,
    scale: number,
    opacity: number,
    radius: number,
    modeB: boolean,
    snap: boolean,
    position: CCPoint,
    oneButton: boolean,
    player2: boolean,
    split: boolean,
}
"""


def _prelude(namespace: str) -> str:
    enum_lines = "\n".join(
        f"export type {name} = number" for name in sorted(enum_lua_names(namespace))
    )
    if namespace == "geode.cocos2d":
        return VALUE_TYPE_STUBS + enum_lines + "\n"
    if enum_lines:
        return enum_lines + "\n"
    return ""


def _header(label: str) -> List[str]:
    return [
        "-- Generated by LuauAPI codegen\n",
        f"-- {label}\n",
        "\n",
    ]


def _object_type_name(info: TypeInfo) -> str:
    if info.class_name:
        return info.class_name
    return info.lua_type.removesuffix("?")


def _refs_from_method(
    method: Method, objects: Dict[str, Class]
) -> tuple[set[str], set[str]]:
    object_refs: set[str] = set()
    value_refs: set[str] = set()
    for arg in method.args:
        info = classify_arg(arg.type, objects)
        if not info:
            continue
        if info.kind == "object":
            object_refs.add(_object_type_name(info))
        elif info.kind == "value":
            value_refs.add(info.lua_type)
    ret = classify_return(method.ret, objects)
    if ret:
        if ret.kind == "object":
            object_refs.add(_object_type_name(ret))
        elif ret.kind == "value":
            value_refs.add(ret.lua_type)
    return object_refs, value_refs


def _base_type_refs(
    cls: Class, objects: Dict[str, Class], skipped_classes: set
) -> set[str]:
    refs: set[str] = set()
    for base in cls.bases:
        base_cls = objects.get(short_name(base))
        if base_cls and base_cls.name not in skipped_classes:
            refs.add(base_cls.name)
    return refs


def _external_type_refs(
    classes: Sequence[Class],
    grouped_by_class: Dict[str, Dict[str, List[Method]]],
    objects: Dict[str, Class],
    skipped_classes: set,
    source_namespace: str,
) -> set[str]:
    refs: set[str] = set()
    for cls in classes:
        if cls.name in skipped_classes or lua_namespace(cls) != source_namespace:
            continue
        refs.update(_base_type_refs(cls, objects, skipped_classes))
        for methods in grouped_by_class[cls.name].values():
            for method in methods:
                object_refs, _ = _refs_from_method(method, objects)
                refs.update(object_refs)
    external: set[str] = set()
    for name in refs:
        ref_cls = objects.get(name)
        if ref_cls and lua_namespace(ref_cls) != source_namespace:
            external.add(name)
    return external


def _external_value_refs(
    classes: Sequence[Class],
    grouped_by_class: Dict[str, Dict[str, List[Method]]],
    objects: Dict[str, Class],
    skipped_classes: set,
    source_namespace: str,
) -> set[str]:
    refs: set[str] = set()
    for cls in classes:
        if cls.name in skipped_classes or lua_namespace(cls) != source_namespace:
            continue
        for methods in grouped_by_class[cls.name].values():
            for method in methods:
                _, value_refs = _refs_from_method(method, objects)
                refs.update(value_refs)
    return refs


def _emit_forward_decls(names: set[str], label: str) -> str:
    if not names:
        return ""
    lines = [f"-- Forward declarations for types defined in {label}\n", "\n"]
    for name in sorted(names):
        lines.append(f"declare class {name} end\n\n")
    return "".join(lines)


def _emit_value_stubs(names: set[str]) -> str:
    if not names:
        return ""
    lines = [f"\n-- Value types defined in geode_cocos2d.d.luau\n", "\n"]
    for name in sorted(names):
        if name == "RGBColor":
            lines.append("export type RGBColor = { r: number, g: number, b: number }\n")
        elif name == "CCSize":
            lines.append("export type CCSize = { width: number, height: number }\n")
        elif name == "CCPoint":
            lines.append("export type CCPoint = { x: number, y: number }\n")
        elif name == "CCRect":
            lines.append("export type CCRect = { origin: CCPoint, size: CCSize }\n")
        elif name == "UIButtonConfig":
            lines.append(
                "export type UIButtonConfig = {\n"
                "    width: number,\n"
                "    height: number,\n"
                "    deadzone: number,\n"
                "    scale: number,\n"
                "    opacity: number,\n"
                "    radius: number,\n"
                "    modeB: boolean,\n"
                "    snap: boolean,\n"
                "    position: CCPoint,\n"
                "    oneButton: boolean,\n"
                "    player2: boolean,\n"
                "    split: boolean,\n"
                "}\n"
            )
    lines.append("\n")
    return "".join(lines)


def _emit_class(
    cls: Class,
    grouped: Dict[str, List[Method]],
    objects: Dict[str, Class],
    skipped_classes: set,
) -> List[str]:
    lines: List[str] = []
    base = ""
    for b in cls.bases:
        b_cls = objects.get(short_name(b))
        if b_cls and b_cls.name not in skipped_classes:
            base = f" extends {b_cls.name}"
            break
    instance_methods = {
        k: v
        for k, v in grouped.items()
        if not v[0].is_static and k not in LUAU_KEYWORDS
    }
    if not instance_methods:
        lines.append(f"declare class {cls.name}{base} end\n\n")
    else:
        lines.append(f"declare class {cls.name}{base}\n")
        for name, methods in sorted(instance_methods.items()):
            if len(methods) == 1:
                m = methods[0]
                args = _classify_input_args(m, objects)
                ret_type = _method_return_type(cls, m, objects)
                arg_text = ", ".join(
                    f"arg{i}: {arg.lua_type}" for i, arg in enumerate(args, start=1)
                )
                joiner = ", " if arg_text else ""
                self_prefix = "" if m.is_static else f"self{joiner}"
                if m.is_static:
                    lines.append(
                        f"    function {name}({arg_text}){': ' + ret_type if ret_type != '()' else ''}\n"
                    )
                else:
                    lines.append(
                        f"    function {name}({self_prefix}{arg_text}){': ' + ret_type if ret_type != '()' else ''}\n"
                    )
            else:
                lines.append(f"    {name}: {_method_type(cls, methods, objects)}\n")
        lines.append("end\n\n")
    return lines


def emit(root: Root, target_platform: str = "win") -> Dict[str, str]:
    classes = object_classes(root)
    objects = codegen_object_map(root)
    grouped_by_class: Dict[str, Dict[str, List[Method]]] = {}
    skipped_by_class: Dict[str, List[tuple[Method, str]]] = {}
    factories: Dict[str, Dict[str, List[Method]]] = defaultdict(dict)

    for cls in classes:
        grouped, cls_skipped = group_supported(cls, objects, target_platform)
        grouped_by_class[cls.name] = grouped
        skipped_by_class[cls.name] = cls_skipped

    skipped_classes = linkless_class_names(
        classes, objects, grouped_by_class, skipped_by_class, target_platform
    )
    prune_skipped_class_refs(
        grouped_by_class,
        skipped_by_class,
        objects,
        skipped_classes,
        target_platform,
    )

    cocos_namespace = "geode.cocos2d"
    gd_namespace = "geode.gd"

    cocos_lines = _header("Cocos2d class declarations")
    cocos_lines.append(_prelude(cocos_namespace))
    cocos_lines.append("\n")
    cocos_external = _external_type_refs(
        classes, grouped_by_class, objects, skipped_classes, cocos_namespace
    )
    cocos_lines.append(_emit_forward_decls(cocos_external, "geode_gd.d.luau"))

    gd_lines = _header("Geometry Dash class declarations")
    gd_lines.append(_prelude(gd_namespace))
    gd_external = _external_type_refs(
        classes, grouped_by_class, objects, skipped_classes, gd_namespace
    )
    gd_value_refs = _external_value_refs(
        classes, grouped_by_class, objects, skipped_classes, gd_namespace
    )
    gd_lines.append(_emit_value_stubs(gd_value_refs))
    gd_lines.append(_emit_forward_decls(gd_external, "geode_cocos2d.d.luau"))

    for cls in classes:
        if cls.name in skipped_classes:
            continue
        grouped = grouped_by_class[cls.name]
        cls_lines = _emit_class(cls, grouped, objects, skipped_classes)

        if lua_namespace(cls) == "geode.cocos2d":
            cocos_lines.extend(cls_lines)
        else:
            gd_lines.extend(cls_lines)

        static_methods = {
            k: v
            for k, v in grouped.items()
            if v[0].is_static and k not in LUAU_KEYWORDS
        }
        if static_methods:
            factories[cls.name] = static_methods

    main_external: set[str] = set()
    for methods in factories.values():
        for overloads in methods.values():
            for method in overloads:
                object_refs, _ = _refs_from_method(method, objects)
                main_external.update(object_refs)

    main_lines = _header("Factories and namespace types")
    main_lines.append(
        _emit_forward_decls(main_external, "geode_gd.d.luau and geode_cocos2d.d.luau")
    )
    main_lines.append("export type HookHandle = {\n")
    main_lines.append("    enable: (self: HookHandle) -> boolean,\n")
    main_lines.append("    disable: (self: HookHandle) -> boolean,\n")
    main_lines.append("    remove: (self: HookHandle) -> boolean,\n")
    main_lines.append("    isEnabled: (self: HookHandle) -> boolean,\n")
    main_lines.append("}\n\n")

    for cls_name, methods in sorted(factories.items()):
        main_lines.append(f"export type {cls_name}Factory = {{\n")
        for name, overloads in sorted(methods.items()):
            main_lines.append(
                f"    {name}: {_method_type(objects[cls_name], overloads, objects)},\n"
            )
        main_lines.append("}\n\n")

    cocos = []
    gd = []
    for cls in classes:
        if cls.name in skipped_classes:
            continue
        factory = f"{cls.name}Factory" if cls.name in factories else "{}"
        if lua_namespace(cls) == "geode.cocos2d":
            cocos.append((cls.name, factory))
        else:
            gd.append((cls.name, factory))

    main_lines.append("export type Cocos2dNamespace = {\n")
    for name, factory in sorted(cocos):
        main_lines.append(f"    {name}: {factory},\n")
    main_lines.append("}\n\n")

    main_lines.append("export type GDNamespace = {\n")
    for name, factory in sorted(gd):
        main_lines.append(f"    {name}: {factory},\n")
    main_lines.append("}\n\n")

    main_lines.append("export type GeodeNamespace = {\n")
    main_lines.append("    cocos2d: Cocos2dNamespace,\n")
    main_lines.append("    gd: GDNamespace,\n")
    main_lines.append(
        "    hook: (target: string, callback: (...any) -> ()) -> HookHandle,\n"
    )
    main_lines.append("}\n\n")
    main_lines.append("declare geode: GeodeNamespace\n")

    return {
        "geode_cocos2d.d.luau": "".join(cocos_lines),
        "geode_gd.d.luau": "".join(gd_lines),
        "geode.d.luau": "".join(main_lines),
    }
