from __future__ import annotations

# Manually maintained, you can try removing some but it would probably break.

INACCESSIBLE_METHODS = {
    ("CCActionManager", "update"),
    ("CCAnimationCache", "parseVersion1"),
    ("CCAnimationCache", "parseVersion2"),
    ("CCAtlasNode", "calculateMaxItems"),
    ("CCAtlasNode", "setIgnoreContentScaleFactor"),
    ("CCAtlasNode", "updateBlendFunc"),
    ("CCAtlasNode", "updateOpacityModifyRGB"),
    ("CCBMFontConfiguration", "parseCommonArguments"),
    ("CCBMFontConfiguration", "parseImageFileName"),
    ("CCBMFontConfiguration", "parseInfoArguments"),
    ("CCBMFontConfiguration", "parseKerningEntry"),
    ("CCBMFontConfiguration", "purgeFontDefDictionary"),
    ("CCBMFontConfiguration", "purgeKerningDictionary"),
    (
        "CCControlPotentiometer",
        "angleInDegreesBetweenLineFromPoint_toPoint_toLineFromPoint_toPoint",
    ),
    ("CCControl", "create"),
    ("CCControlColourPicker", "ccTouchBegan"),
    ("CCControlColourPicker", "updateControlPicker"),
    ("CCControlColourPicker", "updateHueAndControlPicker"),
    ("CCControlHuePicker", "ccTouchBegan"),
    ("CCControlHuePicker", "ccTouchMoved"),
    ("CCControlHuePicker", "checkSliderPosition"),
    ("CCControlHuePicker", "updateSliderPosition"),
    ("CCControlPotentiometer", "distanceBetweenPointAndPoint"),
    ("CCControlPotentiometer", "potentiometerBegan"),
    ("CCControlPotentiometer", "potentiometerEnded"),
    ("CCControlPotentiometer", "potentiometerMoved"),
    ("CCControlSaturationBrightnessPicker", "ccTouchBegan"),
    ("CCControlSaturationBrightnessPicker", "ccTouchMoved"),
    ("CCControlSaturationBrightnessPicker", "checkSliderPosition"),
    ("CCControlSaturationBrightnessPicker", "updateSliderPosition"),
    ("CCControlSlider", "sliderBegan"),
    ("CCControlSlider", "sliderEnded"),
    ("CCControlSlider", "sliderMoved"),
    ("CCControlSlider", "valueForLocation"),
    ("CCDictionary", "setObjectUnSafe"),
    ("CCDirector", "calculateDeltaTime"),
    ("CCDirector", "calculateMPF"),
    ("CCDirector", "createStatsLabel"),
    ("CCDirector", "purgeDirector"),
    ("CCDirector", "setNextScene"),
    ("CCDirector", "showStats"),
    ("CCDrawNode", "ensureCapacity"),
    ("CCDrawNode", "render"),
    ("CCGLProgram", "description"),
    ("CCLabelTTF", "updateTexture"),
    ("CCLayer", "excuteScriptTouchHandler"),
    ("CCLayerColor", "updateColor"),
    ("CCLabelBMFont", "getLetterPosXLeft"),
    ("CCLabelBMFont", "getLetterPosXRight"),
    ("CCLabelBMFont", "kerningAmountForFirst"),
    ("CCMenu", "itemForTouch"),
    ("CCMenuItemFont", "recreateLabel"),
    ("CCMenuItemSprite", "updateImagesVisibility"),
    ("CCNode", "childrenAlloc"),
    ("CCNode", "convertToWindowSpace"),
    ("CCNode", "detachChild"),
    ("CCNode", "insertChild"),
    ("CCNode", "resetGlobalOrderOfArrival"),
    ("CCNotificationCenter", "observerExisted"),
    ("CCParallaxNode", "absolutePosition"),
    ("CCParticleBatchNode", "addChildHelper"),
    ("CCParticleBatchNode", "increaseAtlasCapacityTo"),
    ("CCParticleBatchNode", "searchNewPositionInChildrenForZ"),
    ("CCParticleBatchNode", "updateAllAtlasIndexes"),
    ("CCParticleBatchNode", "updateBlendFunc"),
    ("CCParticleSystem", "updateBlendFunc"),
    ("CCParticleSystemQuad", "allocMemory"),
    ("CCParticleSystemQuad", "setupVBO"),
    ("CCParticleSystemQuad", "setupVBOandVAO"),
    ("CCProgressTimer", "boundaryTexCoord"),
    ("CCProgressTimer", "updateBar"),
    ("CCProgressTimer", "updateColor"),
    ("CCProgressTimer", "updateProgress"),
    ("CCProgressTimer", "updateRadial"),
    ("CCRenderTexture", "beginWithClear"),
    ("CCScale9Sprite", "updateCapInset"),
    ("CCScale9Sprite", "updatePositions"),
    ("CCScrollView", "afterDraw"),
    ("CCScrollView", "beforeDraw"),
    ("CCScrollView", "deaccelerateScrolling"),
    ("CCScrollView", "getViewRect"),
    ("CCScrollView", "performedAnimatedScroll"),
    ("CCScrollView", "relocateContainer"),
    ("CCScrollView", "stoppedAnimatedScroll"),
    ("CCScheduler", "scheduleScriptFunc"),
    ("CCScheduler", "unscheduleScriptEntry"),
    ("CCShaderCache", "init"),
    ("CCShaderCache", "loadDefaultShader"),
    ("CCSprite", "setDirtyRecursively"),
    ("CCSprite", "setReorderChildDirtyRecursively"),
    ("CCSprite", "setTextureCoords"),
    ("CCSprite", "updateBlendFunc"),
    ("CCSprite", "updateColor"),
    ("CCSpriteBatchNode", "addSpriteWithoutQuad"),
    ("CCSpriteBatchNode", "insertQuadFromSprite"),
    ("CCSpriteBatchNode", "swap"),
    ("CCSpriteBatchNode", "updateBlendFunc"),
    ("CCSpriteBatchNode", "updateQuadFromSprite"),
    ("CCSpriteFrameCache", "addSpriteFramesWithDictionary"),
    ("CCSpriteFrameCache", "removeSpriteFramesFromDictionary"),
    ("CCTMXLayer", "appendTileForGID"),
    ("CCTMXLayer", "atlasIndexForExistantZ"),
    ("CCTMXLayer", "atlasIndexForNewZ"),
    ("CCTMXLayer", "calculateLayerOffset"),
    ("CCTMXLayer", "insertTileForGID"),
    ("CCTMXLayer", "parseInternalProperties"),
    ("CCTMXLayer", "positionForHexAt"),
    ("CCTMXLayer", "positionForIsoAt"),
    ("CCTMXLayer", "positionForOrthoAt"),
    ("CCTMXLayer", "reusedTileWithRect"),
    ("CCTMXLayer", "setupTileSprite"),
    ("CCTMXLayer", "updateTileForGID"),
    ("CCTMXLayer", "vertexZForPos"),
    ("CCTMXMapInfo", "internalInit"),
    ("CCTMXTiledMap", "buildWithMapInfo"),
    ("CCTMXTiledMap", "parseLayer"),
    ("CCTMXTiledMap", "tilesetForLayer"),
    ("CCTableView", "__indexFromOffset"),
    ("CCTableView", "__offsetFromIndex"),
    ("CCTableView", "_addCellIfNecessary"),
    ("CCTableView", "_indexFromOffset"),
    ("CCTableView", "_moveCellOutOfSight"),
    ("CCTableView", "_offsetFromIndex"),
    ("CCTableView", "_setIndexForCell"),
    ("CCTableView", "_updateCellPositions"),
    ("CCTextFieldTTF", "canAttachWithIME"),
    ("CCTextFieldTTF", "canDetachWithIME"),
    ("CCTextFieldTTF", "deleteBackward"),
    ("CCTextFieldTTF", "deleteForward"),
    ("CCTextFieldTTF", "draw"),
    ("CCTextFieldTTF", "getContentText"),
    ("CCTextFieldTTF", "insertText"),
    ("CCTexture2D", "initPremultipliedATextureWithImage"),
    ("CCTextureAtlas", "fillWithEmptyQuadsFromIndex"),
    ("CCTextureAtlas", "mapBuffers"),
    ("CCTextureAtlas", "setupIndices"),
    ("CCTextureAtlas", "setupVBO"),
    ("CCTextureAtlas", "setupVBOandVAO"),
    ("CCTextureCache", "addImageAsyncCallBack"),
    ("CCTextureETC", "loadTexture"),
    ("CCTileMapAtlas", "calculateItemsToRender"),
    ("CCTileMapAtlas", "loadTGAfile"),
    ("CCTileMapAtlas", "updateAtlasValueAt"),
    ("CCTileMapAtlas", "updateAtlasValues"),
    ("CCTouchDispatcher", "decrementForcePrio"),
    ("CCTouchDispatcher", "findHandler"),
    ("CCTouchDispatcher", "forceAddHandler"),
    ("CCTouchDispatcher", "forceRemoveAllDelegates"),
    ("CCTouchDispatcher", "forceRemoveDelegate"),
    ("CCTouchDispatcher", "incrementForcePrio"),
    ("CCTouchDispatcher", "rearrangeHandlers"),
    ("CCTransitionFadeTR", "sceneOrder"),
    ("CCTransitionPageTurn", "sceneOrder"),
    ("CCTransitionProgress", "progressTimerNodeWithRenderTexture"),
    ("CCTransitionProgress", "sceneOrder"),
    ("CCTransitionProgress", "setupTransition"),
    ("CCTransitionProgressHorizontal", "progressTimerNodeWithRenderTexture"),
    ("CCTransitionProgressInOut", "progressTimerNodeWithRenderTexture"),
    ("CCTransitionProgressInOut", "sceneOrder"),
    ("CCTransitionProgressInOut", "setupTransition"),
    ("CCTransitionProgressOutIn", "progressTimerNodeWithRenderTexture"),
    ("CCTransitionProgressRadialCCW", "progressTimerNodeWithRenderTexture"),
    ("CCTransitionProgressRadialCW", "progressTimerNodeWithRenderTexture"),
    ("CCTransitionProgressVertical", "progressTimerNodeWithRenderTexture"),
    ("CCTransitionScene", "sceneOrder"),
    ("CCTransitionScene", "setNewScene"),
    ("CCTransitionSlideInB", "sceneOrder"),
    ("CCTransitionSlideInL", "sceneOrder"),
    ("CCTransitionSlideInR", "sceneOrder"),
    ("CCTransitionSlideInT", "sceneOrder"),
    ("CCTransitionTurnOffTiles", "sceneOrder"),
    ("EditorUI", "onToggleTraceIn"),
    ("EditorUI", "onToggleTraceOut"),
    ("EnterEffectObject", "init"),
    ("GJTransformControl", "calculateRotationOffset"),
    ("GJTransformControl", "finishTouch"),
    ("GJTransformControl", "logCurrentZeroPos"),
    ("GJTransformControl", "spriteByTag"),
    ("GJTransformControl", "updateMinMaxPositions"),
    ("GameLevelManager", "hasLikedItemFullCheck"),
    ("SongSelectNode", "onSongMode"),
    ("EditorUI", "colorSelectClosed"),
    ("EditorUI", "findSnapObject"),
    ("ButtonSprite", "init"),
    ("MDPopup", "void"),
}

INACCESSIBLE_CLASSES = {
    "CCGrabber",
    "CCParticleBatchNode",
    "CCProfilingTimer",
    "CCSchedulerScriptHandlerEntry",
    "CCScriptHandlerEntry",
    "CCStandardTouchHandler",
    "CCTargetedTouchHandler",
    "CCTexturePVR",
    "CCTouchScriptHandlerEntry",
}

# For overloads with the same argument count, only one can bind in Lua.
# PREFERRED_OVERLOADS specifies the preferred argument signatures (normalized form) to keep.
# Others are skipped as `overload-superseded:<arity>`.
# Preference is given to script-friendly and `create` forms.
# Please don't add new entries to this dict without a good reason.
PREFERRED_OVERLOADS: dict[tuple[str, str], set[tuple[str, ...]]] = {
    ("EditorUI", "getSpriteButton"): {
        (
            "char const*",
            "cocos2d::SEL_MenuHandler",
            "cocos2d::CCMenu*",
            "float",
            "int",
            "cocos2d::CCPoint",
        ),
    },
    ("CCNode", "removeComponent"): {("char const*",)},
    ("CCSpriteFrameCache", "addSpriteFramesWithFile"): {
        ("char const*", "char const*"),
    },
    ("CCMotionStreak", "create"): {
        ("float", "float", "float", "cocos2d::ccColor3B const&", "char const*"),
    },
    ("CCMotionStreak", "initWithFade"): {
        ("float", "float", "float", "cocos2d::ccColor3B const&", "char const*"),
    },
    ("CCScale9Sprite", "create"): {("char const*", "cocos2d::CCRect")},
    ("CCScale9Sprite", "initWithFile"): {("char const*", "cocos2d::CCRect")},
    ("CCLabelAtlas", "initWithString"): {
        ("char const*", "char const*", "unsigned int", "unsigned int", "unsigned int"),
    },
    ("CCControlSlider", "create"): {("char const*", "char const*", "char const*")},
    ("GameLevelManager", "getSavedLevel"): {("int",)},
    ("SongInfoObject", "create"): {("int",)},
    ("GameObject", "slopeYPos"): {("float",)},
    ("LabelGameObject", "updateLabel"): {("gd::string",)},
    ("ButtonSprite", "create"): {
        ("char const*",),
        ("cocos2d::CCSprite*", "int", "bool", "float", "char const*", "float"),
        ("char const*", "int", "bool", "char const*", "char const*", "float", "float"),
        (
            "char const*",
            "int",
            "int",
            "float",
            "bool",
            "char const*",
            "char const*",
            "float",
        ),
    },
    ("ScrollLayer", "create"): {("cocos2d::CCSize const&", "bool", "bool")},
    ("Notification", "create"): {("ZStringView", "NotificationIcon", "float")},
    ("Notification", "setIcon"): {("NotificationIcon",)},
    ("ColorPickPopup", "create"): {("bool",)},
    ("ColorSelectPopup", "create"): {("cocos2d::ccColor3B",)},
    ("CCMenuItemSprite", "create"): {
        ("cocos2d::CCNode*", "cocos2d::CCNode*", "cocos2d::CCNode*"),
    },
    ("CCMenuItemImage", "create"): {
        ("char const*", "char const*", "char const*"),
    },
    ("Border", "setPadding"): {("float",)},
    ("GJItemIcon", "darkenStoreItem"): {("ShopType",)},
    ("GJSmartBlockPreview", "addTemplateGuide"): {("SmartPrefabResult", "float")},
}

# Constructors are blocked unless listed here. Use for rare cases where static `create()` is unavailable or filtered out.
# Only include classes where `new T(args)` produces a valid, ready-to-use object. Destructors are never bindable.
BINDABLE_CONSTRUCTORS: dict[str, set[tuple[str, ...]]] = {}
